gui-init changes: -uniformize requests to hit Enter to user's prompts -replicate required steps needed to release TPM key into LUKS header's slot1. --This required unseal-totp first. Doh.

diff --git a/initrd/bin/gui-init b/initrd/bin/gui-init
--- a/initrd/bin/gui-init
+++ b/initrd/bin/gui-init
@@ -257,17 +257,58 @@ check_onboarding_progress()
 mount_boot 
 if [ -e /boot/reset_disk_unlock_key ]; then
   whiptail $CONFIG_WARNING_BG_COLOR --clear --title 'WARNING: You must change your disk unlock key passphrase' --msgbox \
-    "You just generated a new TOTP/HOTP secret. TPM released disk unlock key\n won't work anymore and must be recreated.\n To do so, select a new default boot option, and agree to modify the disk." 30 90
+    "You just generated a new TOTP/HOTP secret. TPM released disk unlock key\n stored in LUKS header must be regenerated.\n\nTo do so, select a new default boot option and agree to:\n -Modify the disk\n -Reseal disk key to the TPM.\n -Sign config changes with your GPG card user's PIN" 30 90
   # Try to select a kernel from the menu
-    mount_boot
-    verify_global_hashes
-    if [ $? -ne 0 ]; then
-      continue
-    fi
-    kexec-select-boot -m -b /boot -c "grub.cfg" -g
+  mount_boot
+  verify_global_hashes
+  if [ $? -ne 0 ]; then
     continue
+  fi
+ 
+  if [ "$CONFIG_TPM" = n ]; then
+      TOTP="NO TPM"
+  else
+    TOTP=`unseal-totp`
+    if [ $? -ne 0 ]; then
+      echo "Error generating TOTP code. We will regenerate it now."
+      update_totp
+      continue
+    elif [ -x /bin/libremkey_hotp_verification ]; then
+      HOTP=`unseal-hotp`
+      enable_usb
+      if ! libremkey_hotp_verification info ; then
+        whiptail $CONFIG_WARNING_BG_COLOR --clear --title 'WARNING: Please Insert Your Librem Key' --msgbox "Your Librem Key was not detected.\n\nPlease insert your Librem Key" 30 90
+      fi
+      # Don't output HOTP codes to screen, so as to make replay attacks harder
+      libremkey_hotp_verification check $HOTP
+      case "$?" in
+        0 )
+          HOTP="Success"
+        ;;
+        4 )
+          HOTP="Invalid code"
+          MAIN_MENU_BG_COLOR=$CONFIG_ERROR_BG_COLOR
+        ;;
+        * )
+          HOTP="Error checking code, Insert Librem Key and retry"
+          MAIN_MENU_BG_COLOR=$CONFIG_WARNING_BG_COLOR
+        ;;
+        esac
+    else
+      HOTP='N/A'
+    fi
+      
+    if [ $HOTP = "Success" ];then
+      kexec-select-boot -m -b /boot -c "grub.cfg" -g
+      continue
+    else
+      echo -e "HOTP status:" $HOTP "\n\nHit Enter to regenerate new TOTP/HOTP codes."
+      read
+      update_totp
+    fi
+    continue
+  fi
 fi
-
 
 last_half=X
 while true; do
@@ -340,7 +381,7 @@ while true; do
     if [[ -e /boot/oem ]] && [[ ! -s /boot/oem ]] ;then
       #oem empty file found. Show Onboarding menu once.
       whiptail --title 'Hardware reownership Wizard' --msgbox \
-        "The received hardware is currently owned by your OEM. We will change that.\n\nOn the next screen, MAKE SURE THAT THE HOTP CODE IS: 'Success'\\nIf it's not, reboot your hardware with your Librem/Nitrokey inserted.\nIf the HOTP code is still invalid, return received hardware back to OEM.\n\nThis Wizard would otherwise make you own your own hardware by:\n1-Reencrypting encrypted drive content (LUKS container)\n2-Changing LUKS Recovery key and it's passphrase\n3-Resetting your LibremKey/Nitrokey Pro v2 to factory defaults\n4-Setting User (PIN) and Admin passwords into your LibremKey/NitroKey\n4-Generating keys in it, exporting public key and\n importing it in the rom prior to reprogramming the SPI flash with it\n5-Own your Trusted Platform Module (TPM)\n6-Take integrity measures of all /boot files and sign the resulting\n checksum file with yourLibremKey/Nitrokey Pro\n\nPress the Enter key to continue." 30 60
+        "The received hardware is currently owned by your OEM. We will change that.\n\nOn the next screen, MAKE SURE THAT THE HOTP CODE IS: 'Success'\\nIf it's not, reboot your hardware with your Librem/Nitrokey inserted.\nIf the HOTP code is still invalid, return received hardware back to OEM.\n\nThis Wizard would otherwise make you own your own hardware by:\n1-Reencrypting encrypted drive content (LUKS container)\n2-Changing LUKS Recovery key and it's passphrase\n3-Resetting your LibremKey/Nitrokey Pro v2 to factory defaults\n4-Setting User (PIN) and Admin passwords into your LibremKey/NitroKey\n4-Generating keys in it, exporting public key and\n importing it in the rom prior to reprogramming the SPI flash with it\n5-Own your Trusted Platform Module (TPM)\n6-Take integrity measures of all /boot files and sign the resulting\n checksum file with yourLibremKey/Nitrokey Pro\n\nHit Enter to continue." 30 60
       totp_confirm="O"
       echo $totp_confirm > /tmp/whiptail
       mount -o remount,rw /boot
@@ -564,7 +605,7 @@ while true; do
       read gpgcard_comment
 
       whiptail $CONFIG_WARNING_BG_COLOR --clear --title 'WARNING: Please Insert A USB Disk' --msgbox \
-      "Please insert a USB disk on which you want to store your GPG public key\n and trustdb.\n\nThose will be backuped under the 'gpg_keys' directory.\n\nPress the Enter key to continue." 30 90     
+      "Please insert a USB disk on which you want to store your GPG public key\n and trustdb.\n\nThose will be backuped under the 'gpg_keys' directory.\n\nHit Enter to continue." 30 90     
       
       #TODO whiptail warning loop
       mount-usb
@@ -583,7 +624,7 @@ while true; do
       
       #Generate Encryption, Signing and Authentication keys
       whiptail --clear --title 'GPG card key generation' --msgbox \
-        "BE PATIENT! Generating 4096 bits Encryption, Signing and Authentication\n keys take around 5 minutes each! Be prepared to patient around 15 minutes!\n\nPress the Enter Key to continue" 30 90
+        "BE PATIENT! Generating 4096 bits Encryption, Signing and Authentication\n keys take around 5 minutes each! Be prepared to patient around 15 minutes!\n\nHit Enter to continue" 30 90
 
       confirm_gpg_card
       {
@@ -672,7 +713,7 @@ while true; do
       fi
       
       whiptail $CONFIG_WARNING_BG_COLOR --clear --title 'WARNING: Reboot required' --msgbox \
-        "A reboot is required.\n\n Your firmware has been reflashed with your own public key and trustdb\n included.\n\n Heads will detect it and react accordingly:\n It will ask you to regenerate a new TOTP/HOTP code (seal BIOS integrity),\n take /boot integrity measures and sign them with your freshly\n factory resetted GPG card user password (PIN).\n\nPress the Enter key to continue." 30 90
+        "A reboot is required.\n\n Your firmware has been reflashed with your own public key and trustdb\n included.\n\n Heads will detect it and react accordingly:\n It will ask you to regenerate a new TOTP/HOTP code (seal BIOS integrity),\n take /boot integrity measures and sign them with your freshly\n factory resetted GPG card user password (PIN).\n\nHit Enter to continue." 30 90
       /bin/reboot
     else
       echo "Returning to the previous menu"
@@ -683,17 +724,17 @@ while true; do
   if [ "$totp_confirm" = "R" ]; then
     if [[ -z $reownership_state ]] || [[ $reownership_state = "luks_reencryption" ]]; then 
       whiptail --title 'Reencrypt LUKS container with a new user selected strong passphrase?' \
-          --msgbox "This will replace the actual Disk recovery key.\n\nThe passphrase associated with this key will be asked to the user in the\n following conditions:\n1-Every boot if no Disk unlock key was added to the TPM\n2-If the TPM fails (Hardware failure)\n3-If the firmware has been tampered with/upgraded/modified by the user\n\nThis process requires you to type the actual Disk recovery key passphrase\nand will delete the actual Disk unlock key released by the TPM into\nLUKS (slot 1) if present.\n\nAt the next prompt, you may be asked to select which file corresponds to\nthe LUKS device container. Normally, it should be /dev/sda2.\n\nPress the Enter key." 30 90
+          --msgbox "This will replace the actual Disk recovery key.\n\nThe passphrase associated with this key will be asked to the user in the\n following conditions:\n1-Every boot if no Disk unlock key was added to the TPM\n2-If the TPM fails (Hardware failure)\n3-If the firmware has been tampered with/upgraded/modified by the user\n\nThis process requires you to type the actual Disk recovery key passphrase\nand will delete the actual Disk unlock key released by the TPM into\nLUKS (slot 1) if present.\n\nAt the next prompt, you may be asked to select which file corresponds to\nthe LUKS device container. Normally, it should be /dev/sda2.\n\nHit Enter to continue." 30 90
     
       select_luks_container
     
       whiptail --title 'Reencrypting LUKS container!' --msgbox \
-      "Please enter current Recovery key passphrase (slot 0) to reencrypt\n LUKS container with a brand new encryption key\n\nPress Enter to continue." 30 60
+      "Please enter current Recovery key passphrase (slot 0) to reencrypt\n LUKS container with a brand new encryption key\n\nHit Enter to continue." 30 60
       cryptsetup-reencrypt -B 32 --use-directio $LUKS --key-slot 0
       
       if [ $(echo $?) -ne 0 ]; then
         whiptail --title 'Invalid LUKS passphrase?' --msgbox \
-          "The LUKS Recovery password was provided to you by the OEM over secure\ncommunication channel.\n\nIf you previously changed it and do not remember it,\n you will have to reinstall Linux OS from a USB drive.\n\nTo do so, place ISO file with it's signature file on root of USB drive,\n and select Boot from USB\n\nPlease press Enter to continue." 30 60
+          "The LUKS Recovery password was provided to you by the OEM over secure\ncommunication channel.\n\nIf you previously changed it and do not remember it,\n you will have to reinstall Linux OS from a USB drive.\n\nTo do so, place ISO file with it's signature file on root of USB drive,\n and select Boot from USB\n\nHit Enter to continue." 30 60
         continue
       else
         #Successfully reencrypted LUKS container with current Recovery key passphrase. Write successful state in oem file
@@ -708,14 +749,14 @@ while true; do
 
     if [[ -z $reownership_state ]] || [[ $reownership_state == "luks_password_change" ]]; then
       whiptail --title 'Changing LUKS Recovery key passphrase' --msgbox \
-        "Please enter current Recovery key passphrase (slot 0).\nThen choose a strong passphrase of your own.\n\n**DICEWARE passphrase methodology is STRONGLY ADVISED.**\n\nPlease hit Enter to continue" 30 60
+        "Please enter current Recovery key passphrase (slot 0).\nThen choose a strong passphrase of your own.\n\n**DICEWARE passphrase methodology is STRONGLY ADVISED.**\n\nHit Enter to continue" 30 60
 
       select_luks_container
     
       cryptsetup luksChangeKey $LUKS --key-slot 0 --tries 3
       if [ $(echo $?) -ne 0 ]; then
         whiptail --title 'Invalid LUKS passphrase?' --msgbox \
-          "The LUKS Recovery password was provided to you by the OEM over secure channel.\nIf you previously changed it and do not remember it,\n you will have to reinstall Linux OS from a USB drive.\nTo do so, put OS ISO file with it's signature file on USB drive,\n And select Boot from USB\n\nPlease press Enter to continue." 30 60
+          "The LUKS Recovery password was provided to you by the OEM over secure channel.\nIf you previously changed it and do not remember it,\n you will have to reinstall Linux OS from a USB drive.\nTo do so, put OS ISO file with it's signature file on USB drive,\n And select Boot from USB\n\nHit Enter to continue." 30 60
         continue
       else
         #Successfully changed passphrase of LUKS Recovery key. Write successful state in oem file
