Bringing back PrivacyBeast scripts, kernel, and renaming board and configs to x230-privacybeast
Base for merging upstream and adapting changes.

diff --git a/initrd/bin/gui-init b/initrd/bin/gui-init
--- a/initrd/bin/gui-init
+++ b/initrd/bin/gui-init
@@ -8,31 +8,24 @@ CONFIG_BOOT_GUI_MENU_NAME='Heads Boot Menu'
 
 mount_boot()
 {
-  
-  # Mount local disk if it is not already mounted
-  while ! grep -q /boot /proc/mounts ; do
-    # ensure default boot device is set
-    if [ ! -e "$CONFIG_BOOT_DEV" ]; then
-      if (whiptail $CONFIG_ERROR_BG_COLOR --clear --title "ERROR: $CONFIG_BOOT_DEV missing!" \
-          --yesno "The /boot device $CONFIG_BOOT_DEV could not be found!\n\nYou will need to configure the correct device for /boot.\n\nWould you like to configure the /boot device now?" 30 90) then
-        config-gui.sh boot_device_select
-      else
-        # exit to main menu
-        break
-      fi
+  # ensure default boot device is set
+  if [ ! -e "$CONFIG_BOOT_DEV" ]; then
+    if (whiptail $CONFIG_ERROR_BG_COLOR --clear --title "ERROR: $CONFIG_BOOT_DEV missing!" \
+    --yesno "The /boot device $CONFIG_BOOT_DEV could not be found!\n\nYou will need to configure the correct device for /boot.\n\nWould you like to configure the /boot device now?" 30 90) then
+    config-gui.sh
     fi
-    # update CONFIG_BOOT_DEV
-    . /tmp/config
-    mount -o ro $CONFIG_BOOT_DEV /boot 
+  # Mount local disk if it is not already mounted
+  elif ! grep -q /boot /proc/mounts ; then
+    mount -o ro /boot 
     if [ $? -ne 0 ]; then
       if (whiptail $CONFIG_ERROR_BG_COLOR --clear --title 'ERROR: Cannot mount /boot' \
       --yesno "The /boot partition at $CONFIG_BOOT_DEV could not be mounted!\n\nWould you like to configure the /boot device now?" 30 90) then
-        config-gui.sh boot_device_select
+        config-gui.sh
       else
         recovery "Unable to mount /boot"
       fi
     fi
-  done
+  fi
 }
 verify_global_hashes()
 {
@@ -47,7 +40,7 @@ verify_global_hashes()
   elif [ ! -f $TMP_HASH_FILE ]; then
     if (whiptail $CONFIG_ERROR_BG_COLOR --clear --title 'ERROR: Missing Hash File!' \
       --yesno "The file containing hashes for /boot is missing!\n\nIf you are setting this system up for the first time, select Yes to update\nyour list of checksums.\n\nOtherwise this could indicate a compromise and you should select No to\nreturn to the main menu.\n\nWould you like to update your checksums now?" 30 90) then
-      prompt_update_checksums
+      update_checksums
     fi
     return 1
   else
@@ -74,16 +67,37 @@ verify_global_hashes()
     fi
 
     if (whiptail $CONFIG_ERROR_BG_COLOR --clear --title 'ERROR: Boot Hash Mismatch' --yesno "$TEXT" 30 90) then
-      prompt_update_checksums
+      update_checksums
     fi
     return 1
   fi
 }
-prompt_update_checksums()
+update_checksums()
 {
   if (whiptail --title 'Update Checksums and sign all files in /boot' \
-      --yesno "You have chosen to update the checksums and sign all of the files in /boot.\n\nThis means that you trust that the files in /boot have not been tampered with.\n\nYou will need your GPG key to continue and this change will modify your disk.\n\nDo you want to continue?" 16 90) then
-    update_checksums
+      --yesno "You have chosen to update the checksums and sign all of the files in /boot.\n\nThis means that you trust that the files in /boot have not been tampered\n with.\n\nYou will need your GPG key to continue and this change will modify your\n disk.\n\nDo you want to continue?" 16 90) then
+    mount_boot
+    mount -o rw,remount /boot
+
+    cd /boot
+    find ./ -type f ! -name '*kexec*' | xargs sha256sum > /boot/kexec_hashes.txt
+    DEFAULT_FILES=$(cat /boot/kexec_default_hashes.txt | cut -f3 -d ' ')
+    echo $DEFAULT_FILES | xargs sha256sum > /boot/kexec_default_hashes.txt
+
+    # Remove any package trigger log files
+    # We don't need them after the user decides to sign
+    rm -f /boot/kexec_package_trigger*
+
+    # sign and auto-roll config counter
+    extparam=
+    if [ "$CONFIG_TPM" = "y" ]; then
+      extparam=-u
+    fi
+    kexec-sign-config -p /boot $extparam \
+    || die "Failed to sign default config"
+
+    # switch back to ro mode
+    mount -o ro,remount /boot
   else
     echo "Returning to the main menu"
   fi
@@ -91,54 +105,50 @@ prompt_update_checksums()
 update_totp()
 {
   echo "Scan the QR code to add the new TOTP secret"
-  /bin/seal-totp
+  /bin/seal-totp $CONFIG_BOARD
   if [ -x /bin/libremkey_hotp_verification ]; then
     echo "Once you have scanned the QR code, hit Enter to configure your Librem Key"
     read
     /bin/seal-libremkey
+		#Sometimes HOTP sealing fails. We do until it works.
+    while [ $? -ne 0 ];do
+      echo -e "\n\nSealing HOTP secret into Librem Key failed. Let's try again by resealing both TOTP and HOTP."
+      update_totp
+      /bin/seal-libremkey
+    done
   else
-    echo "Once you have scanned the QR code, hit Enter to continue"
+    echo "Once you have scanned the QR code, hit Enter to reboot"
     read
   fi
+  /bin/reboot
 }
 
-clean_boot_check()
-{
-  # assume /boot mounted
-  if ! grep -q /boot /proc/mounts ; then
-    return
-  fi
-
-  # check for any kexec files in /boot
-  kexec_files=`find /boot -name kexec*.txt`
-  [ ! -z "$kexec_files" ] && return
-  
-  #check for GPG key in keyring
-  GPG_KEY_COUNT=`gpg -k 2>/dev/null | wc -l`
-  [ $GPG_KEY_COUNT -ne 0 ] && return
-
-   # check for USB security token
-  if [ "$CONFIG_LIBREMKEY" = "y" ]; then
-    enable_usb
-    if ! gpg --card-status > /dev/null ; then
-      return
+# ensure /boot is sane and mount it
+mount_boot
+if [ -e /boot/oem ];then
+  if [ -z "$oem_configuration_read" ]; then
+    #make sure the system is powered by AC outlet
+    if [ $(cat /sys/class/power_supply/AC/online) -eq 1 ]; then
+      #Read /media/oem-provisioning file once to read provisioned secrets
+      read_oem_files
+    else
+      notify "You must run the Reownership Wizard from a safe place with power outlet connected. OEM Reownership will require around an hour. Sytem will now power off."
+      poweroff
     fi
   fi
-
-  # OS is installed, no kexec files present, no GPG keys in keyring, security token present
-  # prompt user to run OEM factory reset
-  oem-factory-reset \
-    "Clean Boot Detected - Perform OEM Factory Reset?" "$CONFIG_WARNING_BG_COLOR"
-}
-
-if detect_boot_device ; then
-  # /boot device with installed OS found
-  clean_boot_check
-else
-  # can't determine /boot device or no OS installed, 
-  # so fall back to interactive selection
-  mount_boot
 fi
+
+if [ -e /boot/reset_disk_unlock_key ] && [ ! -e /boot/oem ]; then
+  if (whiptail $CONFIG_WARNING_BG_COLOR --title "WARNING: You must change your Disk Unlock Key" \
+        --yesno "You just updated the ROM, which requires resealing TOTP/HOTP secrets.\nTPM released Disk Unlock Key stored in LUKS header must also be regenerated.\n\nIf you did not modify the ROM, this might be a sign of system compromise.\nIn that case, you should say No here and investigate." 30 90) then
+    reset_disk_unlock_key
+  else
+    recovery "User refused to update TOTP/HOTP following what seemed to be a ROM update. Time to investigate changes manually."
+  fi
+fi
+
+# enable USB to load modules for external kb
+enable_usb
 
 last_half=X
 while true; do
@@ -169,14 +179,8 @@ while true; do
       TOTP=`unseal-totp`
       if [ $? -ne 0 ]; then
         whiptail $CONFIG_ERROR_BG_COLOR --clear --title "ERROR: TOTP Generation Failed!" \
-          --menu "    ERROR: Heads couldn't generate the TOTP code.\n
-    If you have just completed a Factory Reset, or just reflashed
-    your BIOS, you should generate a new HOTP/TOTP secret.\n
-    If this is the first time the system has booted, you should
-    reset the TPM and set your own password.\n
-    If you have not just reflashed your BIOS, THIS COULD INDICATE TAMPERING!\n
-    How would you like to proceed?" 30 90 4 \
-          'g' ' Generate new HOTP/TOTP secret' \
+          --menu "ERROR: Heads couldn't generate the TOTP code.\n\nIf this is the first time the system has booted, you should reset the TPM\nand set your own password\n\nIf you just reflashed your BIOS, you'll need to generate a new TOTP secret.\n\nIf you have not just reflashed your BIOS, THIS COULD INDICATE TAMPERING!\n\nHow would you like to proceed?" 30 90 4 \
+          'g' ' Generate new TOTP/HOTP secret' \
           'i' ' Ignore error and continue to default boot menu' \
           'p' ' Reset the TPM' \
           'x' ' Exit to recovery shell' \
@@ -213,27 +217,57 @@ while true; do
       HOTP='N/A'
     fi
 
-    whiptail $MAIN_MENU_BG_COLOR --clear --title "$CONFIG_BOOT_GUI_MENU_NAME" \
+    if [ -e /boot/oem ]; then
+      check_onboarding_progress
+  	  totp_confirm="O"
+      echo $totp_confirm > /tmp/whiptail
+    else
+          whiptail $MAIN_MENU_BG_COLOR --clear --title "$CONFIG_BOOT_GUI_MENU_NAME" \
       --menu "$date\nTOTP: $TOTP | HOTP: $HOTP" 20 90 10 \
       'y' ' Default boot' \
       'r' ' Refresh TOTP/HOTP' \
-      'a' ' Options -->' \
+      'a' ' Settings -->' \
       'P' ' Power Off' \
       2>/tmp/whiptail || recovery "GUI menu failed"
 
-    totp_confirm=$(cat /tmp/whiptail)
+      totp_confirm=$(cat /tmp/whiptail)
+    fi
+  fi
+
+  if [ "$totp_confirm" = "O" ]; then
+    check_config /boot force
+    TMP_HASH_FILE="/tmp/kexec/kexec_hashes.txt"
+
+    if cd /boot && sha256sum -c "$TMP_HASH_FILE" > /tmp/hash_output ; then
+      HASH="OK"
+      #Else there is errors from cryptsetup-reencrypt complaining to not be able to create logfile
+      cd /
+    else
+     HASH="ALTERED" 
+    fi
+    
+    whiptail $MAIN_MENU_BG_COLOR --clear --title "$CONFIG_BOOT_GUI_MENU_NAME: Reownership" \
+        --menu "Greenwich Mean Time (GMT) : $date\nTOTP: $TOTP | HOTP: $HOTP | /BOOT INTEGRITY: $HASH" 20 90 10 \
+        'C' ' Continue ownership of devices' \
+        'x' ' Exit to recovery shell' \
+        2>/tmp/whiptail || recovery "GUI menu failed"
+      totp_confirm=$(cat /tmp/whiptail)
+  fi
+
+  if [ "$totp_confirm" = "C" ]; then
+    check_onboarding_progress
   fi
 
   if [ "$totp_confirm" = "a" ]; then
-    whiptail --clear --title "HEADS Options" \
-      --menu "" 20 90 10 \
-      'o' ' Boot Options -->' \
+    whiptail --clear --title "Settings" \
+      --menu "Configure Settings" 20 90 10 \
+      'o' ' Other Boot Options -->' \
       't' ' TPM/TOTP/HOTP Options -->' \
       's' ' Update checksums and sign all files in /boot' \
       'c' ' Change configuration settings -->' \
       'f' ' Flash/Update the BIOS -->' \
       'G' ' GPG Options -->' \
-      'F' ' OEM Factory Reset -->' \
+      'R' ' Reencrypt LUKS container' \
       'x' ' Exit to recovery shell' \
       'r' ' <-- Return to main menu' \
       2>/tmp/whiptail || recovery "GUI menu failed"
@@ -242,10 +276,11 @@ while true; do
   fi
 
   if [ "$totp_confirm" = "o" ]; then
-    whiptail --clear --title "Boot Options" \
+    whiptail --clear --title "Other Boot Options" \
       --menu "Select A Boot Option" 20 90 10 \
       'm' ' Show OS boot menu' \
       'u' ' USB boot' \
+      'z' ' SDCARD boot' \
       'i' ' Ignore tampering and force a boot (Unsafe!)' \
       'r' ' <-- Return to main menu' \
       2>/tmp/whiptail || recovery "GUI menu failed"
@@ -292,6 +327,13 @@ while true; do
     continue
   fi
 
+  if [ "$totp_confirm" = "z" ]; then
+    mount-sdcard
+    exec /bin/usb-init
+    continue
+  fi
+
+
   if [ "$totp_confirm" = "g" ]; then
     if (whiptail --title 'Generate new TOTP/HOTP secret' \
         --yesno "This will erase your old secret and replace it with a new one!\n\nDo you want to proceed?" 16 90) then
@@ -306,6 +348,14 @@ while true; do
     if (whiptail --title 'Reset the TPM' \
         --yesno "This will clear the TPM and TPM password, replace them with new ones!\n\nDo you want to proceed?" 16 90) then
       /bin/tpm-reset
+      
+      #set flag in oem file
+      mount_boot
+      if [ -s /boot/oem ];then
+        mount -o remount,rw /boot
+        echo "tpm_reowned" >> /boot/oem
+        mount -o remount,ro /boot
+      fi
 
       # now that the TPM is reset, remove invalid TPM counter files
       mount_boot
@@ -355,7 +405,7 @@ while true; do
   fi
 
   if [ "$totp_confirm" = "s" ]; then
-    prompt_update_checksums
+    update_checksums
     continue
   fi
 
@@ -374,8 +424,8 @@ while true; do
     continue
   fi
 
-  if [ "$totp_confirm" = "F" ]; then
-    oem-factory-reset
+  if [ "$totp_confirm" = "R" ]; then
+    /bin/reencrypt-luks
     continue
   fi
 
diff --git a/initrd/bin/seal-libremkey b/initrd/bin/seal-libremkey
--- a/initrd/bin/seal-libremkey
+++ b/initrd/bin/seal-libremkey
@@ -59,15 +59,16 @@ if ! libremkey_hotp_verification info ; then
   fi
 fi
 
-echo -e ""
-read -s -p "Enter your Librem Key Admin PIN: " admin_pin
-echo -e "\n"
+if [ -z "$oem_gpg_Admin_PIN" ]; then
+  read -s -p "Enter your Librem Key Admin PIN" admin_pin
+  echo
+else
+  admin_pin=$(echo -n "$oem_gpg_Admin_PIN")
+fi
 
 libremkey_hotp_initialize "$admin_pin" $HOTP_SECRET $counter_value 
 if [ $? -ne 0 ]; then
-  echo -e "\n"
-  read -s -p "Error setting HOTP secret, re-enter Admin PIN and try again: " admin_pin
-  echo -e "\n"
+  read -s -p "Error setting HOTP secret, re-enter Admin PIN and try again:" admin_pin
   if ! libremkey_hotp_initialize "$admin_pin" $HOTP_SECRET $counter_value ; then
     # don't leak key on failure
     shred -n 10 -z -u "$HOTP_SECRET" 2> /dev/null
@@ -88,13 +89,13 @@ mount -o remount,rw /boot
 
 counter_value=`expr $counter_value + 1`
 echo $counter_value > $HOTP_COUNTER \
-|| die "Unable to create hotp counter file"
+|| die "Unable to create HOTP counter file"
 
 #sha256sum /tmp/counter-$counter > $HOTP_COUNTER \
-#|| die "Unable to create hotp counter file"
+#|| die "Unable to create HOTP counter file"
 mount -o remount,ro /boot
 
-echo -e "\nLibrem Key initialized successfully. Press Enter to continue."
+echo "Librem Key initialized successfully. Press Enter to continue."
 read
 
 exit 0
