Update reownership language
Major changes:
- Removed mention of "Librem Key." Replaced with "HOTP-enabled USB security token."
- Specifies that resealing TOTP/HOTP during reownership is normal.
- Emphasize that missing /boot record is normal during reownership wizard (`initrd/bin/gui-init`).

Minor changes:

- Shortened sentences.
  - Where appropriate, cause is placed before effect. (For example,"Both your TOTP/HOTP codes and TPM released Disk Unlock Key were invalidated since measured boot integrity changed" is now "Measured boot integrity chagned. Both your TOTP/HOTP codes and TPM released Disk Unlock Key were invalidated").
- Renamed term "actual" to "existing" (e.g., "existing Disk Recovery Key" instead of "actual Disk Recovery Key").
- Changes to past tense instead of nouns (e.g., "failed to unlock" instead of "failure to unlock"), for consistency.
- Changes voice to second-person for consistency.
- Corrects capitalization.
- Changes lists to be consistently formatted.
- Changes terms to consistent names (e.g., "email" instead of "e-mail").
- Corrects grammar and punctuation.

diff --git a/initrd/bin/kexec-insert-key b/initrd/bin/kexec-insert-key
--- a/initrd/bin/kexec-insert-key
+++ b/initrd/bin/kexec-insert-key
@@ -42,12 +42,12 @@ mkdir -p "$INITRD_DIR/etc"
 unseal_failed="n"
 if ! kexec-unseal-key "$INITRD_DIR/secret.key" ; then
 	unseal_failed="y"
-	echo "!!! Failed to unseal the TPM LUKS Disk Unlock Key"
+	echo "!!! Failed to unseal the TPM LUKS Disk Unlock Key."
 fi
 
 # Override PCR 4 so that user can't read the key
 tpm extend -ix 4 -ic generic \
-	|| die 'Unable to scramble PCR'
+	|| die 'Unable to scramble PCR.'
 
 # Check to continue
 if [ "$unseal_failed" = "y" ]; then
@@ -61,7 +61,7 @@ if [ "$unseal_failed" = "y" ]; then
 		-a "$confirm_boot" != 'Y' \
 		-a -n "$confirm_boot" ] \
 	; then
-		die "!!! Aborting boot due to failure to unseal TPM Disk Unlock Key"
+		die "!!! Failed to unseal TPM Disk Unlock Key. Aborting boot."
 	fi
 fi
 
diff --git a/initrd/bin/kexec-save-key b/initrd/bin/kexec-save-key
--- a/initrd/bin/kexec-save-key
+++ b/initrd/bin/kexec-save-key
@@ -29,7 +29,7 @@ paramsdir="${paramsdir%%/}"
 
 if [ -n "$lvm_volume_group" ]; then
 	lvm vgchange -a y $lvm_volume_group \
-	|| die "Failed to activate the LVM group"
+	|| die "Failed to activate the LVM group."
 
 	for dev in /dev/$lvm_volume_group/*; do
 		key_devices="$key_devices $dev"
@@ -46,7 +46,7 @@ mount -o rw,remount $paramsdev
 rm -f $paramsdir/kexec_key_lvm.txt || true
 if [ -n "$lvm_volume_group" ]; then
 	echo "$lvm_volume_group" > $paramsdir/kexec_key_lvm.txt \
-	|| die "Failed to write lvm group to key config "
+	|| die "Failed to write LVM group to key config."
 fi
 
 rm -f $paramsdir/kexec_key_devices.txt || true
@@ -58,12 +58,12 @@ for dev in $key_devices; do
 done
 
 kexec-seal-key $paramsdir \
-|| die "Failed to save and generate key in TPM"
+|| die "Failed to save and generate key in TPM."
 
 if [ "$skip_sign" != "y" ]; then
 	# sign and auto-roll config counter
 	kexec-sign-config -p $paramsdir -u \
-	|| die "Failed to sign updated config"
+	|| die "Failed to sign updated config."
 fi
 
 # switch back to ro mode
diff --git a/initrd/bin/kexec-seal-key b/initrd/bin/kexec-seal-key
--- a/initrd/bin/kexec-seal-key
+++ b/initrd/bin/kexec-seal-key
@@ -22,7 +22,7 @@ KEY_DEVICES="$paramsdir/kexec_key_devices.txt"
 KEY_LVM="$paramsdir/kexec_key_lvm.txt"
 
 if [ ! -r "$KEY_DEVICES" ]; then
-	die "No devices defined for disk encryption"
+	die "No devices defined for disk encryption."
 fi
 
 if [ -r "$KEY_LVM" ]; then
@@ -72,7 +72,7 @@ dd \
 	bs=1 \
 	count=128 \
 	2>/dev/null \
-|| die "Unable to generate 128 random bytes"
+|| die "Unable to generate 128 random bytes."
 
 # Remove all the old keys from slot 1
 for dev in `cat "$KEY_DEVICES" | cut -d\  -f1`; do
@@ -80,14 +80,14 @@ for dev in `cat "$KEY_DEVICES" | cut -d\  -f1`; do
   cryptsetup luksKillSlot \
     --key-file "$RECOVERY_KEY" \
     $dev 1 \
-  || warn "Removing LUKS Disk Unlock Key on $dev (key slot 1) failed. Bad passphrase or key slot 1 not existing. Continuing..."
+  || warn "Removing LUKS Disk Unlock Key on $dev (key slot 1) failed. Bad passphrase or key slot 1 doesn't exist. Continuing..."
 
   echo "++++++ $dev: Adding key"
   cryptsetup luksAddKey \
     --key-file "$RECOVERY_KEY" \
     --key-slot 1 \
     $dev "$KEY_FILE" \
-  || die "Unable to add key to $dev key slot 1. Please try again with actual LUKS Disk Recovery Key passphrase."
+  || die "Unable to add key to $dev key slot 1. Please try again with existing LUKS Disk Recovery Key passphrase."
 done
 
 # Now that we have setup the new keys, measure the PCRs
@@ -98,8 +98,8 @@ cat "$KEY_DEVICES" | cut -d\  -f1 | xargs /bin/qubes-measure-luks \
 	|| die "Unable to measure the LUKS headers"
 luks_pcr=`tpm calcfuturepcr -ix 16 -if /tmp/luksDump.txt`
 
-# Librem Key loads USB modules which changes PCR5.
-# In the event Librem Key is enabled, skip verification of PCR5
+# HOTP-enabled USB security token loads USB modules which changes PCR5.
+# In the event HOTP-enabled USB security token is enabled, skip verification of PCR5
 if [ -x /bin/libremkey_hotp_verification ]; then
   pcr_5="X"
 else
@@ -132,7 +132,7 @@ tpm sealfile2 \
 || die "Unable to seal secret"
 
 shred -n 10 -z -u "$KEY_FILE" 2> /dev/null \
-|| die "Failed to delete key file"
+|| die "Failed to delete key file."
 
 # try it without the owner password first
 if ! tpm nv_writevalue \
@@ -145,7 +145,7 @@ if ! tpm nv_writevalue \
 	# The permissions are 0 since there is nothing special
 	# about the sealed file
 	tpm physicalpresence -s \
-	|| warn "Warning: Unable to assert physical presence"
+	|| warn "Warning: Unable to assert physical presence."
   
   if [ -z "$oem_TPM_Owner_Password" ]; then
 	  read -s -p "TPM Owner passphrase: " tpm_password
@@ -159,7 +159,7 @@ if ! tpm nv_writevalue \
 		-sz $TPM_SIZE \
 		-pwdo "$tpm_password" \
 		-per 0 \
-	|| warn "Warning: Unable to define NVRAM space; trying anyway"
+	|| warn "Warning: Unable to define NVRAM space. Trying anyway."
 
 
 	tpm nv_writevalue \
diff --git a/initrd/bin/seal-libremkey b/initrd/bin/seal-libremkey
--- a/initrd/bin/seal-libremkey
+++ b/initrd/bin/seal-libremkey
@@ -12,7 +12,7 @@ mount_boot()
   # Mount local disk if it is not already mounted
   if ! grep -q /boot /proc/mounts ; then
     mount -o ro /boot \
-      || recovery "Unable to mount /boot"
+      || recovery "Unable to mount /boot."
   fi
 }
 
@@ -20,13 +20,13 @@ tpm nv_readvalue \
 	-in 4d47 \
 	-sz 312 \
 	-of "$HOTP_SEALED" \
-|| die "Unable to retrieve sealed file from TPM NV"
+|| die "Unable to retrieve sealed file from TPM NV."
 
 tpm unsealfile  \
 	-hk 40000000 \
 	-if "$HOTP_SEALED" \
 	-of "$HOTP_SECRET" \
-|| die "Unable to unseal HOTP secret"
+|| die "Unable to unseal HOTP secret."
 
 shred -n 10 -z -u "$HOTP_SEALED" 2> /dev/null
 
@@ -50,17 +50,17 @@ counter_value=1
 
 enable_usb
 if ! libremkey_hotp_verification info ; then
-  echo "Insert your Librem Key and press Enter to configure it"
+    echo "Insert your HOTP-enabled USB security token and press Enter to configure it."
   read
   if ! libremkey_hotp_verification info ; then
     # don't leak key on failure
     shred -n 10 -z -u "$HOTP_SECRET" 2> /dev/null
-    die "Unable to find Librem Key"
+    die "Unable to find HOTP-enabled USB token."
   fi
 fi
 
 if [ -z "$oem_gpg_Admin_PIN" ]; then
-  read -s -p "Enter your Librem Key Admin PIN" admin_pin
+  read -s -p "Enter your HOTP-enabled USB security token's Admin PIN." admin_pin
   echo
 else
   admin_pin=$(echo -n "$oem_gpg_Admin_PIN")
@@ -68,7 +68,7 @@ fi
 
 libremkey_hotp_initialize "$admin_pin" $HOTP_SECRET $counter_value 
 if [ $? -ne 0 ]; then
-  read -s -p "Error setting HOTP secret, re-enter Admin PIN and try again:" admin_pin
+  read -s -p "Error setting HOTP secret. Re-enter Admin PIN and try again:" admin_pin
   if ! libremkey_hotp_initialize "$admin_pin" $HOTP_SECRET $counter_value ; then
     # don't leak key on failure
     shred -n 10 -z -u "$HOTP_SECRET" 2> /dev/null
@@ -89,13 +89,13 @@ mount -o remount,rw /boot
 
 counter_value=`expr $counter_value + 1`
 echo $counter_value > $HOTP_COUNTER \
-|| die "Unable to create HOTP counter file"
+|| die "Unable to create HOTP counter file."
 
 #sha256sum /tmp/counter-$counter > $HOTP_COUNTER \
 #|| die "Unable to create HOTP counter file"
 mount -o remount,ro /boot
 
-echo "Librem Key initialized successfully. Press Enter to continue."
+echo "HOTP-enabled USB security token initialized successfully. Press Enter to continue."
 read
 
 exit 0
diff --git a/initrd/bin/uefi-init b/initrd/bin/uefi-init
--- a/initrd/bin/uefi-init
+++ b/initrd/bin/uefi-init
@@ -16,13 +16,13 @@ if [ -n "GUID" ]; then
 	echo "Loading $GUID from ROM"
 	TMPFILE=/tmp/uefi.$$
 	uefi -r $GUID | gunzip -c > $TMPFILE \
-	|| die "Failed to read config GUID from ROM"
+	|| die "Failed to read config GUID from ROM."
 
 	if [ "$CONFIG_TPM" = "y" ]; then
 		tpm extend -ix "$CONFIG_PCR" -if $TMPFILE \
-		|| die "$filename: tpm extend failed"
+		|| die "$filename: tpm extend failed."
 	fi
 
 	( cd / ; cpio -iud < $TMPFILE 2>/dev/null ) \
-	|| die "Failed to extract config GUID"
+	|| die "Failed to extract config GUID."
 fi
diff --git a/initrd/bin/unseal-hotp b/initrd/bin/unseal-hotp
--- a/initrd/bin/unseal-hotp
+++ b/initrd/bin/unseal-hotp
@@ -12,7 +12,7 @@ mount_boot_or_die()
   # Mount local disk if it is not already mounted
   if ! grep -q /boot /proc/mounts ; then
     mount -o ro /boot \
-      || die "Unable to mount /boot"
+      || die "Unable to mount /boot."
   fi
 }
 
@@ -25,13 +25,13 @@ tpm nv_readvalue \
 	-in 4d47 \
 	-sz 312 \
 	-of "$HOTP_SEALED" \
-|| die "Unable to retrieve sealed file from TPM NV"
+|| die "Unable to retrieve sealed file from TPM NV."
 
 tpm unsealfile  \
 	-hk 40000000 \
 	-if "$HOTP_SEALED" \
 	-of "$HOTP_SECRET" \
-|| die "Unable to unseal HOTP secret"
+|| die "Unable to unseal HOTP secret."
 
 shred -n 10 -z -u "$HOTP_SEALED" 2> /dev/null
 
@@ -46,7 +46,7 @@ shred -n 10 -z -u "$HOTP_SEALED" 2> /dev/null
 counter_value=$(cat $HOTP_COUNTER)
 
 if [ "$counter_value" == "" ]; then
-  die "Unable to read HOTP counter"
+  die "Unable to read HOTP counter."
 fi
 
 #counter_value=$(printf "%d" 0x${counter_value})
@@ -65,7 +65,7 @@ mount -o remount,rw /boot
 
 counter_value=`expr $counter_value + 1`
 echo $counter_value > $HOTP_COUNTER \
-|| die "Unable to create HOTP counter file"
+|| die "Unable to create HOTP counter file."
 
 #sha256sum /tmp/counter-$counter > $HOTP_COUNTER \
 #|| die "Unable to create HOTP counter file"
diff --git a/initrd/bin/usb-scan b/initrd/bin/usb-scan
--- a/initrd/bin/usb-scan
+++ b/initrd/bin/usb-scan
@@ -7,13 +7,13 @@ set -e -o pipefail
 # Unmount any previous boot device
 if grep -q /boot /proc/mounts ; then
 	umount /boot \
-		|| die "Unable to unmount /boot"
+		|| die "Unable to unmount /boot."
 fi
 
 # Mount the USB boot device
 if ! grep -q /media /proc/mounts ; then
 	mount-usb \
-		|| die "Unable to mount /media"
+		|| die "Unable to mount /media."
 fi
 
 # Check for ISO first
@@ -28,10 +28,10 @@ get_menu_option() {
 			MENU_OPTIONS="$MENU_OPTIONS $n ${option}"
 		done < /tmp/iso_menu.txt
 
-		whiptail --clear --title "Select your ISO boot option" \
+		whiptail --clear --title "Select your ISO boot option." \
 			--menu "Choose the ISO boot option [1-$n, s for standard boot, a to abort]:" 20 120 8 \
 			-- $MENU_OPTIONS \
-			2>/tmp/whiptail || die "Aborting boot attempt"
+			2>/tmp/whiptail || die "Aborting boot attempt."
 
 		option_index=$(cat /tmp/whiptail)
 	else
@@ -49,7 +49,7 @@ get_menu_option() {
 	fi
 
 	if [ "$option_index" = "a" ]; then
-		die "Aborting boot attempt"
+		die "Aborting boot attempt."
 	fi
 
 	if [ "$option_index" = "s" ]; then
@@ -74,7 +74,7 @@ if [ `cat /tmp/iso_menu.txt | wc -l` -gt 0 ]; then
 		ISO=${option:7} # remove /media/ to get device relative path
 		kexec-iso-init $MOUNTED_ISO $ISO $(grep "/media" /proc/mounts | awk -F " " '{print $1}')
 
-		die "Something failed in iso init"
+		die "Something failed in ISO init."
 	fi
 fi
 
@@ -86,4 +86,4 @@ else
 	kexec-select-boot -b /media -c "*.cfg" -u -s
 fi
 
-die "Something failed in selecting boot"
+die "Something failed in selecting boot."
