General proper error handling Luks disk unlock key defaults to Y when /boot/kexec_key_devices.txt exist, created by selecting a boot default Added execution of config-gui when configured usb device is not found under gpg-gui, flash-gui and factory-reset-nitrokey-libremkey.sh Revalidated the workflow of HOTP sealing, which sometimes don't work. I fixed this by looping into TOTP resealing prior to HOTP. Not doing so goes to actual HOTP code which retries only once and die, leaving the TOTP sealed and HOTP unsealed. As reported, the actual loop can take up to 4x before working. A bug report has been made to Nitrokey: https://github.com/Nitrokey/nitrokey-hotp-verification/issues/6 And some other minor fixes

diff --git a/initrd/bin/kexec-insert-key b/initrd/bin/kexec-insert-key
--- a/initrd/bin/kexec-insert-key
+++ b/initrd/bin/kexec-insert-key
@@ -23,7 +23,7 @@ if [ -r "$TMP_KEY_LVM" ]; then
 		die "No LVM volume group defined for activation"
 	fi
 	lvm vgchange -a y $VOLUME_GROUP \
-		|| die "$VOLUME_GROUP: unable to activate volume group"
+		|| die "$VOLUME_GROUP: Unable to activate volume group"
 fi
 
 # Measure the LUKS headers before we unseal the disk key
diff --git a/initrd/bin/kexec-seal-key b/initrd/bin/kexec-seal-key
--- a/initrd/bin/kexec-seal-key
+++ b/initrd/bin/kexec-seal-key
@@ -32,7 +32,7 @@ if [ -r "$KEY_LVM" ]; then
 		die "No LVM volume group defined for activation"
 	fi
 	lvm vgchange -a y $VOLUME_GROUP \
-		|| die "$VOLUME_GROUP: unable to activate volume group"
+		|| die "$VOLUME_GROUP: Unable to activate volume group"
 fi
 
 # Key slot 0 is the manual recovery pass phrase
diff --git a/initrd/bin/mount-usb b/initrd/bin/mount-usb
--- a/initrd/bin/mount-usb
+++ b/initrd/bin/mount-usb
@@ -11,11 +11,11 @@ if ! lsmod | grep -q usb_storage; then
 fi
 
 if [ ! -d /media ]; then
-	mkdir /media
+	mkdir /media || die "Unable to create /media directory"
 fi
 
 if [ -z "$1" ]; then
-	mount -o ro /media
+	mount -o ro /media || die "Unable to mount /media in Read Only mode"
 else
-	mount -o ro $1 /media
+	mount -o ro $1 /media || die "unable to mount $1 on /media in Read Only mode"
 fi
