Addressing review and fix TPM counter file bugs
Signed-off-by: Thierry Laurion <insurgo@riseup.net>

diff --git a/initrd/bin/kexec-sign-config b/initrd/bin/kexec-sign-config
--- a/initrd/bin/kexec-sign-config
+++ b/initrd/bin/kexec-sign-config
@@ -63,54 +63,60 @@ if [ "$update" = "y" ]; then
 fi
 
 if [ "$rollback" = "y" ]; then
-
-    # this script was called with -c $OPTARG (counter=$OPTARG) or -r (rollback=y)
-    DEBUG "rollback=y, counter=$counter, paramsdir=$paramsdir"
-    TRACE_FUNC
-
     rollback_file="$paramsdir/kexec_rollback.txt"
 
+    DEBUG "rollback=y, counter=$counter, paramsdir=$paramsdir, rollback_file=$rollback_file"
+    TRACE_FUNC
+
     if [ -n "$counter" ]; then
-        DEBUG "rollback=y: counter=$counter, will read tpm counter next"
+        DEBUG "rollback=y: provided counter=$counter, will read tpm counter next"
         TRACE_FUNC
 
         # use existing tpm counter
-        DO_WITH_DEBUG read_tpm_counter $counter >/dev/null 2>&1 ||
+        DO_WITH_DEBUG read_tpm_counter "$counter" >/dev/null 2>&1 ||
             die "$paramsdir: Unable to read tpm counter '$counter'"
     else
-        DEBUG "rollback=y: counter is empty: checking for existing TPM counter"
+        DEBUG "rollback=y: counter was not provided: checking for existing TPM counter from TPM rollback_file=$rollback_file"
         TRACE_FUNC
 
-        if [ ! -e $rollback_file ]; then
+        if [ -e "$rollback_file" ]; then
+            # Extract TPM_COUNTER from rollback file
+            TPM_COUNTER=$(grep -o 'counter-[0-9a-f]*' "$rollback_file" | cut -d- -f2)
+            DEBUG "rollback=y: Found TPM counter $TPM_COUNTER in rollback file $rollback_file"
+        else
             DEBUG "Rollback file $rollback_file does not exist. Creating new TPM counter."
             DO_WITH_DEBUG check_tpm_counter $rollback_file ||
                 die "$paramsdir: Unable to find/create tpm counter"
 
             TRACE_FUNC
-            DEBUG "rollback=y: checked for existing counter under $rollback_file, found TPM_COUNTER=$TPM_COUNTER"
-            # we checked for existing counter and didn't die; increment it
-            DEBUG "rollback=y: Incrementing counter:$TPM_COUNTER."
-
-            DO_WITH_DEBUG increment_tpm_counter $counter >/dev/null 2>&1 ||
-                die "$paramsdir: Unable to increment tpm counter"
-            TRACE_FUNC
-            DEBUG "rollback=y: Incremented counter $counter"
-        else
-            die "$paramsdir: No rollback file existing. Please reset TPM through the Heads menu: Options -> TPM/TOTP/HOTP Options -> Reset the TPM"
+            TPM_COUNTER=$(cut -d: -f1 </tmp/counter)
+            DEBUG "rollback=y: Created new TPM counter $TPM_COUNTER"
         fi
     fi
 
-    # Ensure the TPM counter file exists
-    DEBUG "Checking if TPM counter file '/tmp/counter-$counter exists."
-    if [ ! -e "/tmp/counter-$counter" ]; then
-        die "$paramsdir: TPM counter file '/tmp/counter-$counter' not found after incrementing."
+    TRACE_FUNC
+
+    # Increment the TPM counter
+    DEBUG "rollback=y: Incrementing counter $TPM_COUNTER."
+    DO_WITH_DEBUG increment_tpm_counter $TPM_COUNTER >/dev/null 2>&1 ||
+        die "$paramsdir: Unable to increment tpm counter"
+
+    # Ensure the incremented counter file exists
+    incremented_counter_file="/tmp/counter-$TPM_COUNTER"
+    if [ ! -e "$incremented_counter_file" ]; then
+        DEBUG "TPM counter file '$incremented_counter_file' not found. Attempting to read it again."
+        DO_WITH_DEBUG read_tpm_counter "$TPM_COUNTER" >/dev/null 2>&1 ||
+            die "$paramsdir: TPM counter file '$incremented_counter_file' not found after incrementing."
     fi
 
+    DEBUG "TPM counter file '$incremented_counter_file' found."
+
     # Create the rollback file
-    sha256sum /tmp/counter-$counter >$rollback_file ||
+    sha256sum "$incremented_counter_file" >$rollback_file ||
         die "$paramsdir: Unable to create rollback file"
 fi
 
+TRACE_FUNC
 param_files=$(find $paramsdir/kexec*.txt)
 if [ -z "$param_files" ]; then
     die "$paramsdir: No kexec parameter files to sign"
