WiP: initial work done. Lotsa TODO to be fixed
Signed-off-by: Thierry Laurion <insurgo@riseup.net>

diff --git a/initrd/bin/kexec-sign-config b/initrd/bin/kexec-sign-config
--- a/initrd/bin/kexec-sign-config
+++ b/initrd/bin/kexec-sign-config
@@ -27,8 +27,10 @@ fi
 paramsdir="${paramsdir%%/}"
 
 assert_signable
+TRACE_FUNC
 
 confirm_gpg_card
+TRACE_FUNC
 
 # remount /boot as rw
 mount -o remount,rw /boot
@@ -36,15 +38,19 @@ mount -o remount,rw /boot
 # update hashes in /boot before signing
 if [ "$update" = "y" ]; then
 	(
+		TRACE_FUNC
+		DEBUG "update=y: Updating kexec hashes in /boot"
 		cd /boot
 		find ./ -type f ! -path './kexec*' -print0 | xargs -0 sha256sum >/boot/kexec_hashes.txt
 		if [ -e /boot/kexec_default_hashes.txt ]; then
+			DEBUG "/boot/kexec_default_hashes.txt exists, updating /boot/kexec_default_hashes.txt"
 			DEFAULT_FILES=$(cat /boot/kexec_default_hashes.txt | cut -f3 -d ' ')
 			echo $DEFAULT_FILES | xargs sha256sum >/boot/kexec_default_hashes.txt
 		fi
 
 		#also save the file & directory structure to detect added files
 		print_tree >/boot/kexec_tree.txt
+		TRACE_FUNC
 	)
 	[ $? -eq 0 ] || die "$paramsdir: Failed to update hashes."
 
@@ -54,23 +60,60 @@ if [ "$update" = "y" ]; then
 fi
 
 if [ "$rollback" = "y" ]; then
+
+	# this script was called with -c $OPTARG (counter=$OPTARG) or -r (rollback=y)
+	# TODO: THIS NEEDS WORK. $counter is empty
+
+	DEBUG "rollback=y, counter=$counter, paramsdir=$paramsdir"
+
+	TRACE_FUNC
 	rollback_file="$paramsdir/kexec_rollback.txt"
 
 	if [ -n "$counter" ]; then
-		# use existing counter
-		read_tpm_counter $counter >/dev/null 2>&1 ||
+		DEBUG "rollback=y: counter=$counter, will read tpm counter next"
+		TRACE_FUNC
+
+		# use existing tpm counter
+		DO_WITH_DEBUG read_tpm_counter $counter >/dev/null 2>&1 ||
 			die "$paramsdir: Unable to read tpm counter '$counter'"
 	else
-		# increment counter
-		check_tpm_counter $rollback_file >/dev/null 2>&1 ||
+		DEBUG "rollback=y: counter is empty: checking for existing TPM counter"
+		TRACE_FUNC
+
+		if [ ! -e $rollback_file ]; then
+			die "$paramsdir: No rollback file existing. Please reset TPM"
+			#TODO maybe whiptail, die messages are not user friendly
+		fi
+
+		TRACE_FUNC
+		#DO_WITH_DEBUG check_tpm_counter $rollback_file >/dev/null 2>&1 ||
+		#	die "$paramsdir: Unable to find/create tpm counter"
+		DO_WITH_DEBUG check_tpm_counter $rollback_file ||
 			die "$paramsdir: Unable to find/create tpm counter"
 		counter="$TPM_COUNTER"
+		#TODO: this is not working as expected, TPM_COUNTER is empty
 
-		increment_tpm_counter $counter >/dev/null 2>&1 ||
+		# FROM tpm reset:
+		# create Heads TPM counter before any others
+		#check_tpm_counter /boot/kexec_rollback.txt "" "$tpm_owner_password" ||
+		#		die "Unable to find/create tpm counter"
+		#	counter="$TPM_COUNTER"
+
+		DEBUG "rollback=y: checked for existing counter under $rollback_file, found counter:$counter=TPM_COUNTER=$TPM_COUNTER"
+		# we checked for existing counter and didn't die; increment it
+		DEBUG "rollback=y: Incrementing counter:$counter."
+		TRACE_FUNC
+
+		DO_WITH_DEBUG increment_tpm_counter $counter >/dev/null 2>&1 ||
 			die "$paramsdir: Unable to increment tpm counter"
+		
+		DEBUG "rollback=y: Incremented counter $counter"
+		TRACE_FUNC
 	fi
 
-	sha256sum /tmp/counter-$counter >$rollback_file ||
+	# save the counter value to the rollback file
+	DEBUG "rollback=y: Saving counter $counter to $rollback_file"
+	DO_WITH_DEBUG sha256sum /tmp/counter-$counter >$rollback_file ||
 		die "$paramsdir: Unable to create rollback file"
 fi
 
diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -8,6 +8,12 @@ die() {
 	else
 		echo -e "!!! ERROR: $* !!!" >&2
 	fi
+
+	# ask user to press any key prior to exit
+	# TODO: pausing for input creates problems with TPMTOTP unseal and HOTP unseal?!?!
+	#read -n 1 -s -r -p "Press any key to continue..."
+	
+	#TODO remove this sleep and uncomment the read above once figured out.
 	sleep 2
 	exit 1
 }
@@ -762,32 +768,39 @@ check_tpm_counter() {
 	# from it.
 	if [ -r "$1" ]; then
 		TPM_COUNTER=$(grep counter- "$1" | cut -d- -f2)
+		DEBUG "TPM counter found in $1: $TPM_COUNTER"
 	else
 		INFO "$1 does not exist; creating new TPM counter"
-		tpmr counter_create \
+		DO_WITH_DEBUG tpmr counter_create \
 			-pwdc '' \
 			-la $LABEL |
 			tee /tmp/counter >/dev/null 2>&1 ||
 			die "Unable to create TPM counter"
 		TPM_COUNTER=$(cut -d: -f1 </tmp/counter)
+		DEBUG "TPM counter created under /tmp/counter; extracted TPM_COUNTER:$TPM_COUNTER"
+
+		#TPM_COUNTER used from other functions, so export it
+		# TODO: how come this was expected to be valid and not reuse extraction logic leading to TPM_COUNTER being empty?
+		export TPM_COUNTER
+		#TODO clean this mess
 	fi
 
 	if [ -z "$TPM_COUNTER" ]; then
-		die "$1: TPM Counter not found?"
+		die "$1: TPM Counter not found"
 	fi
 }
 
 # Read the TPM counter value from the TPM.
 read_tpm_counter() {
 	TRACE_FUNC
-	tpmr counter_read -ix "$1" | tee "/tmp/counter-$1" >/dev/null 2>&1 ||
+	DO_WITH_DEBUG tpmr counter_read -ix "$1" | tee "/tmp/counter-$1" >/dev/null 2>&1 ||
 		die "Counter read failed"
 }
 
 # Increment the TPM counter value in the TPM.
 increment_tpm_counter() {
 	TRACE_FUNC
-	tpmr counter_increment -ix "$1" -pwdc '' |
+	DO_WITH_DEBUG tpmr counter_increment -ix "$1" -pwdc '' |
 		tee /tmp/counter-$1 >/dev/null 2>&1 ||
 		die "TPM counter increment failed for rollback prevention. Please reset the TPM"
 }
@@ -804,14 +817,17 @@ check_config() {
 	fi
 
 	if [ ! -r $1/kexec.sig -a "$CONFIG_BASIC" != "y" ]; then
+		DEBUG "No $1/kexec.sig found"
 		return
 	fi
 
 	if [ $(find $1/kexec*.txt | wc -l) -eq 0 ]; then
+		DEBUG "No $1/kexec*.txt found"
 		return
 	fi
 
 	if [ "$2" != "force" ]; then
+		DEBUG "$2 != force"
 		# Note that kexec.sig detached signature is solely verifying kexec*.txt files here!
 		if ! sha256sum $(find $1/kexec*.txt) | gpgv $1/kexec.sig -; then
 			die 'Invalid signature on kexec boot params'
@@ -885,10 +901,11 @@ update_checksums() {
 	extparam=
 	if [ "$CONFIG_TPM" = "y" ]; then
 		if [ "$CONFIG_IGNORE_ROLLBACK" != "y" ]; then
+			DEBUG "add -r to kexec-sign-config since CONFIG_IGNORE_ROLLBACK is not set"
 			extparam=-r
 		fi
 	fi
-	if ! kexec-sign-config -p /boot -u $extparam; then
+	if ! DO_WITH_DEBUG kexec-sign-config -p /boot -u $extparam; then
 		rv=1
 	else
 		rv=0
@@ -996,20 +1013,26 @@ verify_checksums() {
 		set +e -o pipefail
 		local ret=0
 		cd "$boot_dir" || ret=1
-		sha256sum -c "$TMP_HASH_FILE" >/tmp/hash_output || ret=1
+		TRACE_FUNC
+		sha256sum -c "$TMP_HASH_FILE" >/tmp/hash_output 2>/dev/null || ret=1
 
 		# also make sure that the file & directory structure didn't change
 		# (sha256sum won't detect added files)
 		print_tree >/tmp/tree_output || ret=1
-		if ! cmp -s "$TMP_TREE_FILE" /tmp/tree_output &>/dev/null; then
+		#if ! cmp -s "$TMP_TREE_FILE" /tmp/tree_output 2>/dev/null; then
+		if ! cmp -s "$TMP_TREE_FILE" /tmp/tree_output; then
+			TRACE_FUNC
 			ret=1
 			[[ "$gui" != "y" ]] && exit "$ret"
 			# produce a diff that can safely be presented to the user
 			# this is relatively hard as file names may e.g. contain backslashes etc.,
 			# which are interpreted by whiptail, less, ...
-			escape_zero "(new) " <"$TMP_TREE_FILE" >"${TMP_TREE_FILE}.user"
+			[ -f "$TMP_TREE_FILE" ] && escape_zero "(new) " <"$TMP_TREE_FILE" >"${TMP_TREE_FILE}.user"
 			escape_zero "(new) " </tmp/tree_output >/tmp/tree_output.user
-			diff "${TMP_TREE_FILE}.user" /tmp/tree_output.user | grep -E '^\+\(new\).*$' | sed -r 's/^\+\(new\)/(new)/g' >>/tmp/hash_output
+			TRACE_FUNC
+			diff "${TMP_TREE_FILE}.user" /tmp/tree_output.user 2>/dev/null |
+				grep -E '^\+(new).*$' | sed -r 's/^\+(new)/(new)/g' >/tmp/tree_output
+			TRACE_FUNC
 			rm -f "${TMP_TREE_FILE}.user"
 			rm -f /tmp/tree_output.user
 		fi
