WIP: secure thumb drive support done. in memory keygen done. backup of key done.
TODO:
- copy key to card support in oem-factory-reset (reset usb security dongle + key to card)
- provision usb security dongle from thumb drive private partition (GPG options -> use backup to provision usb security dongle)
- add temporary usage of thumb drive as smartcard (prompt when usb security dongle not inserted at sign prompt)
- add support for encrypted thumb drive so security dongle is not a requirement

diff --git a/initrd/bin/mount-usb b/initrd/bin/mount-usb
--- a/initrd/bin/mount-usb
+++ b/initrd/bin/mount-usb
@@ -4,17 +4,57 @@
 . /etc/luks-functions
 
 TRACE "Under /bin/mount-usb"
+DEBUG "parameters: [ 1=$1 2=$2 3=$3 4=$4 ]"
 
 enable_usb
 enable_usb_storage
 
-if [ ! -d /media ]; then
-  DEBUG "Creating /media directory"
-  mkdir /media
-else
-  DEBUG "Cleaning /media directory"
-  umount /media > /dev/null 2>&1 || true
+# parameters:
+#   $1: rw or ro
+#   $2: device to mount
+#   $3: mount point
+#   $4: optional: luks password
+
+#show usage when --help is given
+if [ "$1" = "--help" ]; then
+  echo "Usage: mount-usb [rw|ro] [device] [mount point] [luks password]"
+  echo "  ro: mount read-only (default)"
+  echo "  rw: mount read-write"
+  echo "  device: device to mount (default: first USB device found)"
+  echo "  mount point: where to mount the device (default: /media)"
+  echo "  luks password: password for luks device (default: none)"
+  exit 0
 fi
+
+#TODO: works only if rw /dev/sda2 /media pw given.
+#Need to check from 1 arg to 4 args and reset arguments if invalid
+
+if [ -z "$1" ]; then
+        DEBUG "No parameter given, defaulting to read-only"
+        set -- "ro" "$2" "$3" "$4"
+    fi
+
+    if [ "$1" != "ro" ] && [ "$1" != "rw" ]; then
+        DEBUG "Invalid parameter given, defaulting to read-only"
+        set -- "ro" "$2" "$3" "$4"
+    fi
+
+    if [ -z "$2" ]; then
+        DEBUG "No partition given, setting to empty. Will prompt menu to select partition"
+        set -- "$1" "" "$3" "$4"
+    fi
+
+    if [ -z "$3" ]; then
+        DEBUG "No mount point given, defaulting to /media"
+        set -- "$1" "$2" "/media" "$4"
+    fi
+
+    if [ -z "$4" ]; then
+        DEBUG "No luks password given, leaving it optional"
+        set -- "$1" "$2" "$3" "$4"
+    fi
+
+DEBUG "parameters: [ 1=$1 2=$2 3=$3 4=$4 ]"
 
 list_usb_storage > /tmp/usb_block_devices
 if [ -z "$(cat /tmp/usb_block_devices)" ]; then
@@ -27,7 +67,6 @@ if [ -z "$(cat /tmp/usb_block_devices)" ]; then
   fi
   sleep 1
   list_usb_storage > /tmp/usb_block_devices
-
   if [ -z "$(cat /tmp/usb_block_devices)" ]; then
     if [ -x /bin/whiptail ]; then
       whiptail $BG_COLOR_ERROR --title 'ERROR: USB Drive Missing' \
@@ -39,55 +78,64 @@ if [ -z "$(cat /tmp/usb_block_devices)" ]; then
   fi
 fi
 
-
 USB_MOUNT_DEVICE=""
-# Check for the common case: a single USB disk with one partition
-if [ `cat /tmp/usb_block_devices | wc -l` -eq 1 ]; then
-  USB_MOUNT_DEVICE=`cat /tmp/usb_block_devices`
-fi
-# otherwise, let the user pick
-if [ -z ${USB_MOUNT_DEVICE} ]; then
-  > /tmp/usb_disk_list
-  for i in `cat /tmp/usb_block_devices`; do
-    echo $i $(blkid | grep $i | grep -o 'LABEL=".*"' | cut -f2 -d '"') >> /tmp/usb_disk_list
-  done
-
-  if [ -x /bin/whiptail ]; then
-    MENU_OPTIONS=""
-    n=0
-    while read option
-    do
-      n=`expr $n + 1`
-      option=$(echo $option | tr " " "_")
-      MENU_OPTIONS="$MENU_OPTIONS $n ${option}"
-    done < /tmp/usb_disk_list
-
-    MENU_OPTIONS="$MENU_OPTIONS a Abort"
-    whiptail $BG_COLOR --title "Select your USB disk" \
-      --menu "Choose your USB disk [1-$n, a to abort]:" 0 80 8 \
-      -- $MENU_OPTIONS \
-      2>/tmp/whiptail
-
-    option_index=$(cat /tmp/whiptail)
-  else
-    echo "+++ Select your USB disk:"
-    n=0
-    while read option
-    do
-      n=`expr $n + 1`
-      echo "$n. $option"
-    done < /tmp/usb_disk_list
-
-    read \
-      -p "Choose your USB disk [1-$n, a to abort]: " \
-      option_index
+# Check if the user has specified a USB device
+if [ -n "$2" ]; then
+  DEBUG "Checking if $2 is a USB device"
+  if grep -q $2 /tmp/usb_block_devices; then
+    DEBUG "Selected device is a USB device"
+    USB_MOUNT_DEVICE=$2
   fi
-
-  if [ "$option_index" = "a" ]; then
-    exit 5
+else
+  # Check for the common case: a single USB disk with one partition
+  if [ $(cat /tmp/usb_block_devices | wc -l) -eq 1 ]; then
+  USB_MOUNT_DEVICE=$(cat /tmp/usb_block_devices)
   fi
-  USB_MOUNT_DEVICE=`head -n $option_index /tmp/usb_disk_list | tail -1 | sed 's/\ .*$//'`
-fi
+  # otherwise, let the user pick
+  if [ -z ${USB_MOUNT_DEVICE} ]; then
+    > /tmp/usb_disk_list
+    for i in $(cat /tmp/usb_block_devices); do
+      #appends label to the device name
+      echo $i $(blkid | grep $i | grep -o 'LABEL=".*"' | cut -f2 -d '"') >> /tmp/usb_disk_list
+    done
+
+    if [ -x /bin/whiptail ]; then
+      MENU_OPTIONS=""
+      n=0
+      while read option
+      do
+        n=$(expr $n + 1)
+        option=$(echo $option | tr " " "_")
+        MENU_OPTIONS="$MENU_OPTIONS $n ${option}"
+      done < /tmp/usb_disk_list
+
+      MENU_OPTIONS="$MENU_OPTIONS a Abort"
+      whiptail $BG_COLOR --title "Select your USB disk" \
+        --menu "Choose your USB disk [1-$n, a to abort]:" 0 80 8 \
+        -- $MENU_OPTIONS \
+        2>/tmp/whiptail
+
+      option_index=$(cat /tmp/whiptail)
+    else
+      echo "+++ Select your USB disk:"
+      n=0
+      while read option
+      do
+        n=$(expr $n + 1)
+        echo "$n. $option"
+      done < /tmp/usb_disk_list
+
+      read \
+        -p "Choose your USB disk [1-$n, a to abort]: " \
+        option_index
+    fi
+
+    if [ "$option_index" = "a" ]; then
+      exit 5
+    fi
+    USB_MOUNT_DEVICE=$(head -n $option_index /tmp/usb_disk_list | tail -1 | sed 's/\ .*$//')
+  fi
+fi  
 
 # Check if the selected USB partition is a luks device
 # if file exists and not empty, then we have at least one luks device
@@ -102,17 +150,29 @@ if [ -s /tmp/luks_devices ]; then
       cryptsetup luksClose usb_mount_device
     fi
     DEBUG "Opening luks device $USB_MOUNT_DEVICE"
-    cryptsetup luksOpen $USB_MOUNT_DEVICE usb_mount_device
+    #Pass LUKS passphrase to cryptsetup only if we received one
+
+    if [ -z "$4" ]; then
+      #We received a passphrase
+      cryptsetup luksOpen $USB_MOUNT_DEVICE usb_mount_device \
+      || die "Failed to open ${USB_MOUNT_DEVICE} LUKS device"
+    else
+      #Prompt for the pasphrase
+      echo -n "$4"| cryptsetup luksOpen $USB_MOUNT_DEVICE usb_mount_device \
+      || die "Failed to open ${USB_MOUNT_DEVICE} LUKS device"
+    fi
+    
     warn "Note that you cannot boot from a mounted encrypted device."
     DEBUG "Setting USB_MOUNT_DEVICE=/dev/mapper/usb_mount_device"
     USB_MOUNT_DEVICE="/dev/mapper/usb_mount_device"
   fi
 fi
 
+#Reminder : $3 is the mount point
 if [ "$1" = "rw" ]; then
   DEBUG "Mounting $USB_MOUNT_DEVICE as read-write"
-  mount -o rw $USB_MOUNT_DEVICE /media
+  mount -o rw $USB_MOUNT_DEVICE $3
 else
   DEBUG "Mounting $USB_MOUNT_DEVICE as read-only"
-  mount -o ro $USB_MOUNT_DEVICE /media
+  mount -o ro $USB_MOUNT_DEVICE $3
 fi
diff --git a/initrd/etc/luks-functions b/initrd/etc/luks-functions
--- a/initrd/etc/luks-functions
+++ b/initrd/etc/luks-functions
@@ -10,62 +10,41 @@ list_luks_devices()
 {
 	#generate a list of devices to choose from that contain a LUKS header
 	lvm vgscan||true
-        blkid | cut -d ':' -f 1 | while read device;do cryptsetup isLuks $device;if [ $(echo $?) == 0 ]; then echo $device;fi; done | sort
+  blkid | cut -d ':' -f 1 | while read device;do cryptsetup isLuks $device;if [ $(echo $?) == 0 ]; then echo $device;fi; done | sort
 }
 
-#Whiptail warning to disconnect any external storage device
-disconnect_external_storage()
+
+#Whiptail prompt asking user to select ratio of device to use for LUKS container between: 25, 50, 75
+select_luks_container_size_percent()
 {
-	if [ -x /usr/bin/whiptail ]; then
-		whiptail --title 'Disconnect any external storage device' --msgbox \
-			"Please disconnect any external storage device (USB, SD card, etc.)\n\nHit Enter to continue." 30 60
-	else
-		echo "Please disconnect any external storage device (USB, SD card, etc.)"
-		echo "Hit Enter to continue."
-		read
-	fi
-}
-
-#Whiptail warning to connect external storage device
-connect_external_storage()
-{
-	if [ -x /usr/bin/whiptail ]; then
-		whiptail --title 'Connect external storage device' --msgbox \
-			"Please connect external storage device (USB, SD card, etc.)\n\nHit Enter to continue." 30 60
-	else
-		echo "Please connect external storage device (USB, SD card, etc.)"
-		echo "Hit Enter to continue."
-		read
-	fi
-}
-
-#Whiptail prompt asking user to select ratio of device to use for LUKS container between: 25, 50, 75, 100
-select_luks_container_size()
-{	
-	if [ -x /usr/bin/whiptail ]; then
-		whiptail --title 'Select LUKS container size' --menu \
-			"Select the percentage of the device to use for the LUKS container." 30 60 4 \
+	TRACE "Under /etc/luks-functions:select_luks_container_size_percent()"
+	if [ -x /bin/whiptail ]; then
+		#whiptail prompt asking user to select ratio of device to use for LUKS container between: 25, 50, 75
+		#whiptail returns the percentage of the device to use for LUKS container
+		whiptail --title "Select LUKS container size percentage of device" --menu \
+			"Select LUKS container size percentage of device:" 0 80 10 \
 			"25" "25%" \
 			"50" "50%" \
 			"75" "75%" \
-			"100" "100%" 2> /tmp/luks_container_size.txt
+			2> /tmp/luks_container_size_percent \
+			|| die "Error selecting LUKS container size percentage of device"
 	else
-		echo "Select the percentage of the device to use for the LUKS container."
-		echo "1) 25%"
-		echo "2) 50%"
-		echo "3) 75%"
-		echo "4) 100%"
-		read -p "Enter your choice: " choice
-		case $choice in
-			1) echo "25" > /tmp/luks_container_size.txt;;
-			2) echo "50" > /tmp/luks_container_size.txt;;
-			3) echo "75" > /tmp/luks_container_size.txt;;
-			4) echo "100" > /tmp/luks_container_size.txt;;
-			*) echo "Invalid choice";;
+		echo "+++ Select LUKS container size percentage of device:"
+		echo "1. 25%"
+		echo "2. 50%"
+		echo "3. 75%"
+		read \
+			-p "Choose your USB disk [1-3]: " \
+			option_index
+		#translate option_index to percentage
+		case $option_index in
+			1) option_index=25;;
+			2) option_index=50;;
+			3) option_index=75;;
 		esac
+		echo $option_index > /tmp/luks_container_size_percent
 	fi
 }
-
 
 #Partition a device with two partitions: a first one being a LUKS container containing private ext4 partition and second public exfat partition 
 # Size provisioning is done by percentage of the device
@@ -80,29 +59,73 @@ prepare_thumb_drive()
 	PASSPHRASE=$3
 	DEBUG "DEVICE to partition: $DEVICE"
 	DEBUG "PERCENTAGE of device that will be used for LUKS container: $PERCENTAGE"
-	
-	#Create empty DOS partition table on device
-	echo -e "o\nw\n" | fdisk $DEVICE > /dev/null 2>&1 || die "Error creating partition table"
+
+	#Check if device is a block device
+	if [ ! -b $DEVICE ]; then
+		die "Error: $DEVICE is not a block device"
+	fi
+
+	#Check if device is already partitioned with two partitions
+	if [ $(fdisk -l $DEVICE | grep -c "Disklabel type: dos") -eq 2 ]; then
+		warn "Warning: $DEVICE is already partitioned with two partitions"
+	fi
+
+	#Check if device is already partitioned with more than two partitions
+	if [ $(fdisk -l $DEVICE | grep -c "Disklabel type: dos") -gt 2 ]; then
+		warn "Waring: $DEVICE is already partitioned with more than two partitions"
+		#TODO: maybe we want to call sister function to reuse existing partitions?
+	fi
+
+	if [ -z "$PERCENTAGE" ]; then
+		#If no percentage was provided, ask user to select percentage of device to use for LUKS container
+		select_luks_container_size_percent
+		PERCENTAGE=$(cat /tmp/luks_container_size_percent)
+	fi
+
+
 	#Get disk size in bytes from fdisk
 	DISK_SIZE_BYTES=$(fdisk -l $DEVICE | grep Disk | awk -F " " {'print $5'}) > /dev/null 2>&1 || die "Error getting disk size from fdisk"
 	#Convert disk size to MB
 	DISK_SIZE_MB=$(calc $DISK_SIZE_BYTES/1024/1024 | awk -F "." {'print $1'}) > /dev/null 2>&1 || die "Error calculating disk size"
 	#Get size in bytes from percentage and apply percentage to DISK_SIZE_MB
 	PERCENTAGE_MB=$(calc $DISK_SIZE_MB*$PERCENTAGE/100 | awk -F "." {'print $1'}) > /dev/null 2>&1 || die "Error calculating percentage"
-	#partition device with two partitions: first one being the percent applied and rest for second partition
+	
+	#Console and whiptail $BG_COLOR_WARNING prompt (Y/n) validate one last time wiping and repartitioning of $device of total size $DISK_SIZE_MB with $PERCENTAGE_MB assigned to LUKS encrypted private partition
+	if [ -x /bin/whiptail ]; then
+		whiptail $BG_COLOR_WARNING --title "WARNING: Wiping and repartitioning $DEVICE of $DISK_SIZE_MB MB" --yesno \
+			"WARNING: Wiping and repartitioning $DEVICE with $PERCENTAGE_MB MB assigned to private LUKS contained private ext4 partition, rest assigned to extfat public partition.\n\nAre you sure you want to continue?" 0 80 \
+			|| die "User cancelled wiping and repartitioning of $DEVICE"
+	else
+		echo -e -n "Warning: Wiping and repartitioning $DEVICE with $PERCENTAGE_MB MB assigned to private LUKS contained private ext4 partition, rest assigned to extfat public partition.\n\nAre you sure you want to continue?"
+		read -r -p " [Y/n] " response
+		#transform response to uppercase with bash parameter expansion
+		response=${response^^}
+		#continue if response different then uppercase N
+		if [[ $response =~ ^(N)$ ]]; then
+			die "User cancelled wiping and repartitioning of $DEVICE"
+		fi
+	fi
+
+	echo -e "Preparing $DEVICE with $PERCENTAGE_MB MB for private LUKS container and rest of disk with exfat\
+	\n for public partition (This may take a while)..." | fold -s
+	DEBUG "Creating empty DOS partition table on device through fdisk to start clean"
+	echo -e "o\nw\n" | fdisk $DEVICE > /dev/null 2>&1 || die "Error creating partition table"
+	DEBUG "partition device with two partitions: first one being the percent applied and rest for second partition through fdisk"
   	echo -e "n\np\n1\n\n+"$PERCENTAGE_MB"M\nn\np\n2\n\n\nw\n" | fdisk $DEVICE > /dev/null 2>&1 || die "Error partitioning device"
-	#format first partition with LUKS container aes-xts-plain64 cipher with sha256 hash and 512 bit key
+	DEBUG "cryptosetup luksFormat  first partition with LUKS container aes-xts-plain64 cipher with sha256 hash and 512 bit key"
+	DEBUG "Creating ${PERCENTAGE_MB}MB LUKS container on ${DEVICE}1..."
 	echo -n "$PASSPHRASE" \
 		| cryptsetup -c aes-xts-plain64 -h sha256 -s 512 -y luksFormat ${DEVICE}1 > /dev/null 2>&1 \
 		|| die "Error formatting LUKS container"
-	#open LUKS container
+	DEBUG "Opening LUKS device ${DEVICE} into /dev/mapper/private..."
 	echo -n "$PASSPHRASE" | cryptsetup luksOpen ${DEVICE}1 private > /dev/null 2>&1 || die "Error opening LUKS container"
-	#format LUKS container with ext3 filesystem
+	DEBUG "Formatting LUKS device ${DEVICE} mapped under /dev/mapper/private with ext4 partition..."
 	mke2fs -t ext4 -L private /dev/mapper/private > /dev/null 2>&1 || die "Error formatting LUKS container's ext4 filesystem"
-	#close LUKS container
+	DEBUG "Closing LUKS device /dev/mapper/private..."
 	cryptsetup luksClose private > /dev/null 2>&1 || die "Error closing LUKS container"
-	#format second partition with ext3 filesystem
+	DEBUG "Formatting second partition ${DEVICE}2 with exfat filesystem..."
 	mkfs.exfat -L public ${DEVICE}2 > /dev/null 2>&1 || die "Error formatting second partition with exfat filesystem"
+	echo "Done."
 }
 
 select_luks_container()
