mount-usb: refactoring so that arguments are not positional
Next step: have the GPG key backup thumbdrive be useable prompting once dor ADMIN_PIN and propagating to functions

diff --git a/initrd/bin/oem-factory-reset b/initrd/bin/oem-factory-reset
--- a/initrd/bin/oem-factory-reset
+++ b/initrd/bin/oem-factory-reset
@@ -188,9 +188,6 @@ keytocard_subkeys_to_smartcard() {
     gpg_key_factory_reset
 
     DEBUG "Moving subkeys to smartcard..."
-    DEBUG "GPG_USER_MAIL=${GPG_USER_MAIL}"
-    DEBUG "ADMIN_PIN=${ADMIN_PIN}"
-    DEBUG "USER_PIN=${USER_PIN}"
 
         #keytocard all subkeys
         {
@@ -252,81 +249,83 @@ list_blkid_devices() {
 export_master_key_subkeys_and_revocation_key_to_private_LUKS_container() {
     TRACE "Under oem-factory-reset:export_master_key_subkeys_and_revocation_key_to_private_LUKS_container"
 
-    #parameter 1: rw to mount-usb
-    #parameter 2: partition to mount-usb
-    #parameter 3: mount point to mount-usb
-    #parameter 4: luks password (optional)
+    #Sanity check on passed arguments
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -mode)
+                mode="$2"
+                shift
+                shift
+                ;;
+            -device)
+                device="$2"
+                shift
+                shift
+                ;;
+            -mountpoint)
+                mountpoint="$2"
+                shift
+                shift
+                ;;
+            -pass)
+                pass="$2"
+                shift
+                shift
+                ;;
+            *)
+                die "Error: unknown argument: $1"
+                ;;
+        esac
+    done
 
-    if [ -z "$1" ]; then
-        DEBUG "No parameter given, defaulting to read/write"
-        set -- "rw"
-    fi
-
-    if [ "$1" != "ro" ] && [ "$1" != "rw" ]; then
-        DEBUG "Invalid parameter given, defaulting to read/write"
-        set -- "rw"
-    fi
-
-    if [ -z "$2" ]; then
-        DEBUG "No partition given, setting to empty"
-        set -- "$1" "" "$3"
-    fi
-
-    if [ -z "$3" ]; then
-        DEBUG "No mount point given, defaulting to /media"
-        set -- "$1" "$2" "/media"
-    fi
-
-    if [ -z "$4" ]; then
-        DEBUG "No luks password given, leaving optional"
-        set -- "$1" "$2" "$3" "$4"
-    fi
-
-    mount-usb "$1" "$2" "$3" "$4"
+    mount-usb -mode "$mode" -device "$device" -mountpoint "$mountpoint" -pass "$pass"|| die "Error mounting thumb drive's private partition"
 
     #Export master key and subkeys to thumb drive
     DEBUG "Exporting master key and subkeys to private LUKS container's partition..."
-    #DO_WITH_DEBUG gpg --export-secret-keys  --pinentry-mode loopback --passphrase-file <(echo -n "${ADMIN_PIN}") --armor "${GPG_USER_MAIL}" >"$3"/privkey.sec || die "Error exporting master key to private LUKS container's partition"
-    DO_WITH_DEBUG gpg --export-secret-key  --armor --pinentry-mode loopback --passphrase-file <(echo -n "${ADMIN_PIN}") "${GPG_USER_MAIL}" >"$3"/privkey.sec \
+    gpg --export-secret-key  --armor --pinentry-mode loopback --passphrase-file <(echo -n "${pass}") "${GPG_USER_MAIL}" >"$mountpoint"/privkey.sec \
     || die "Error exporting master key to private LUKS container's partition" 
-    #DO_WITH_DEBUG gpg --export-secret-subkeys --pinentry-mode loopback --passphrase-file <(echo -n "${ADMIN_PIN}") --armor "${GPG_USER_MAIL}" >"$3"/subkeys.sec || die "Error exporting subkeys to private LUKS container's partition" 
-    DO_WITH_DEBUG gpg --export-secret-subkeys --armor --pinentry-mode loopback --passphrase-file <(echo -n "${ADMIN_PIN}") "${GPG_USER_MAIL}" >"$3"/subkeys.sec \
+    gpg --export-secret-subkeys --armor --pinentry-mode loopback --passphrase-file <(echo -n "${pass}") "${GPG_USER_MAIL}" >"$mountpoint"/subkeys.sec \
     || die "Error exporting subkeys to private LUKS container's partition"
     #copy whole keyring to thumb drive, including revocation key and trust database
-    cp -af ~/.gnupg "$3"/.gnupg || die "Error copying whole keyring to private LUKS container's partition"
+    cp -af ~/.gnupg "$mountpoint"/.gnupg || die "Error copying whole keyring to private LUKS container's partition"
     #Unmount private LUKS container's mount point
-    umount "$3" || die "Error unmounting private LUKS container's mount point"
+    umount "$mountpoint" || die "Error unmounting private LUKS container's mount point"
 }
 
-#Export public key to thumb drive's publiuc partition
+#Export public key to thumb drive's public partition
 export_public_key_to_thumbdrive_public_partition() {
     TRACE "Under oem-factory-reset:export_public_key_to_thumbdrive_public_partition"
-    if [ -z "$1" ]; then
-        DEBUG "No parameter given, defaulting to read/write"
-        set -- "rw"
-    fi
 
-    if [ "$1" != "ro" ] && [ "$1" != "rw" ]; then
-        DEBUG "Invalid parameter given, defaulting to read/write"
-        set -- "rw"
-    fi
+    #Sanity check on passed arguments
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -mode)
+                mode="$2"
+                shift
+                shift
+                ;;
+            -device)
+                device="$2"
+                shift
+                shift
+                ;;
+            -mountpoint)
+                mountpoint="$2"
+                shift
+                shift
+                ;;
+            *)
+                die "Error: unknown argument: $1"
+                ;;
+        esac
+    done
+    
+    #pass non-empty arguments to -pass,-mountpoint,-device, -mode
+    mount-usb -device "$device" -mode "$mode" -mountpoint "$mountpoint" || die "Error mounting thumb drive's public partition"
 
-    if [ -z "$2" ]; then
-        DEBUG "No partition given, setting to empty"
-        set -- "$1" "" "$3"
-    fi
+    gpg --export --armor "${GPG_USER_MAIL}" >"$mountpoint"/pubkey.asc || die "Error exporting public key to thumb drive's public partition"
 
-    if [ -z "$3" ]; then
-        DEBUG "No mount point given, defaulting to /media"
-        set -- "$1" "$2" "/media"
-    fi
-
-    DEBUG "mount-usb $1 $2 $3"
-    mount-usb "$1" "$2" "$3"
-
-    gpg --export --armor "${GPG_USER_MAIL}" >"$3"/pubkey.asc || die "Error exporting public key to thumb drive's public partition"
-
-    umount "$3" || die "Error unmounting thumb drive's public partition"
+    umount "$mountpoint" || die "Error unmounting thumb drive's public partition"
 }
 
 #Wipe a thumb drive and export master key and subkeys to it
@@ -347,10 +346,10 @@ wipe_thumb_drive_and_copy_gpg_key_material()
     select_luks_container_size_percent
     #Wipe thumb drive with a LUKS container of size $(cat /tmp/luks_container_size_percent)
     prepare_thumb_drive "$thumb_drive" "$(cat /tmp/luks_container_size_percent)" "$ADMIN_PIN"
-    #Export master key and subkeys to thumb drive
-    export_master_key_subkeys_and_revocation_key_to_private_LUKS_container "rw" "$thumb_drive"1 "/media" "$ADMIN_PIN"
+    #Export master key and subkeys to thumb drive first partition
+    export_master_key_subkeys_and_revocation_key_to_private_LUKS_container -mode rw -device "$thumb_drive"1 -mountpoint /media -pass "$ADMIN_PIN"
     #Export public key to thumb drive's public partition
-    export_public_key_to_thumbdrive_public_partition "rw" "$thumb_drive"2 "/media"
+    export_public_key_to_thumbdrive_public_partition -mode rw -device "$thumb_drive"2 -mountpoint /media
 }
 
 gpg_key_factory_reset() {
@@ -866,7 +865,7 @@ if [ "$GPG_GEN_KEY_IN_MEMORY" == "0" ]; then
         # mount USB over /media only if not already mounted
         if ! grep -q /media /proc/mounts; then
             # mount USB in rw
-            if ! mount-usb rw 2>/tmp/error; then
+            if ! mount-usb -mode rw 2>/tmp/error; then
                 ERROR=$(tail -n 1 /tmp/error | fold -s)
                 whiptail_error_die "Unable to mount USB on /media:\n\n${ERROR}"
             fi
