kexec-seal-key: replacing Librem Key -> LibremKey/NitroKey

diff --git a/initrd/bin/seal-libremkey b/initrd/bin/seal-libremkey
--- a/initrd/bin/seal-libremkey
+++ b/initrd/bin/seal-libremkey
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Retrieve the sealed TOTP secret and initialize a Librem Key with it
+# Retrieve the sealed TOTP secret and initialize a LibremKey/NitroKey with it
 
 . /etc/functions
 
@@ -52,13 +52,13 @@ counter_value=1
 
 enable_usb
 if ! libremkey_hotp_verification info ; then
-  echo "Insert your Librem Key and press Enter to configure it"
+  echo "Insert your LibremKey/NitroKey and press Enter to configure it"
   read
   libremkey_hotp_verification info \
-  || die "Unable to find Librem Key"
+  || die "Unable to find LibremKey/NitroKey"
 fi
 
-read -s -p "Enter your Librem Key Admin PIN" admin_pin
+read -s -p "Enter your LibremKey/NitroKey Admin PIN" admin_pin
 echo
 
 libremkey_hotp_initialize $admin_pin $secret $counter_value 
@@ -86,7 +86,7 @@ echo $counter_value > $HOTP_COUNTER \
 #|| die "Unable to create hotp counter file"
 mount -o remount,ro /boot
 
-echo "Librem Key initialized successfully. Press Enter to continue."
+echo "LibremKey/NitroKey initialized successfully. Press Enter to continue."
 read
 
 exit 0
