kgpe-d16: Modifications for unseal-hotp: we want to measure the fallbacks (ramstage,romstage, payload), the microcode, bootblock, and added heads files. Actually, the only thing that cannot be measured here is the s3nv file, since AMD support for relocatable s3 is not yet implementated.
Coreboot producted files:

FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
cbfs master header             0x0        cbfs header        32 none
fallback/romstage              0x80       stage          173132 none
config                         0x2a540    raw               613 none
revision                       0x2a800    raw               561 none
cmos.default                   0x2aa80    cmos_default      256 none
cmos_layout.bin                0x2abc0    cmos_layout      3524 none
fallback/dsdt.aml              0x2b9c0    raw              9895 none
(empty)                        0x2e0c0    null             7384 none
s3nv                           0x2fdc0    raw             65536 none
fallback/ramstage              0x3fe00    stage           88189 none
fallback/payload               0x556c0    simple elf    6313044 none
microcode_amd.bin              0x65ab80   microcode       12684 none
microcode_amd_fam15h.bin       0x65dd80   microcode        7876 none
(empty)                        0x65fcc0   null         10090520 none
bootblock                      0xfff500   bootblock        2232 none

diff --git a/initrd/bin/unseal-hotp b/initrd/bin/unseal-hotp
--- a/initrd/bin/unseal-hotp
+++ b/initrd/bin/unseal-hotp
@@ -6,6 +6,7 @@
 HOTP_SEALED="/tmp/secret/hotp.sealed"
 HOTP_SECRET="/tmp/secret/hotp.key"
 HOTP_COUNTER="/boot/kexec_hotp_counter"
+ROM_IMAGE="/tmp/coreboot-notpm.rom"
 
 mount_boot()
 {
@@ -16,19 +17,31 @@ mount_boot()
   fi
 }
 
-tpm nv_readvalue \
-	-in 4d47 \
-	-sz 312 \
-	-of "$HOTP_SEALED" \
-|| die "Unable to retrieve sealed file from TPM NV"
+if [ "$CONFIG_TPM" = "y" ]; then
+  tpm nv_readvalue \
+    -in 4d47 \
+    -sz 312 \
+    -of "$HOTP_SEALED" \
+  || die "Unable to retrieve sealed file from TPM NV"
 
-tpm unsealfile  \
-	-hk 40000000 \
-	-if "$HOTP_SEALED" \
-	-of "$HOTP_SECRET" \
-|| die "Unable to unseal HOTP secret"
+  tpm unsealfile  \
+    -hk 40000000 \
+    -if "$HOTP_SEALED" \
+    -of "$HOTP_SECRET" \
+  || die "Unable to unseal HOTP secret"
 
-rm -f "$HOTP_SEALED"
+  rm -f "$HOTP_SEALED"
+else
+# without a TPM, use the first 20 characters of the ROM SHA256sum 
+  echo "TPM not configured, measuring ROM directly" 1>&2
+  # use a previously-copied image if it exists
+  #if [ -f ${ROM_IMAGE} ]; then
+  #  sha256sum ${ROM_IMAGE} | cut -f1 -d ' ' | cut -c 1-20 | tr -d '\n' > $HOTP_SECRET
+  #else
+    #flash.sh -s ${ROM_IMAGE} | cut -c 1-20 | tr -d '\n' > $HOTP_SECRET
+  cbfs --list | grep -E 'fallback|heads|microcode|bootblock' | while read CBFS_FILES; do cbfs -o $CBFS_FILES; done | sha256sum | cut -f1 -d ' ' | cut -c 1-20 | tr -d '\n' > $HOTP_SECRET
+  #fi
+fi
 
 # Store counter in file instead of TPM for now, as it conflicts with Heads
 # config TPM counter as TPM 1.2 can only increment one counter between reboots
