/etc/functions: add reseal_tpm_disk_decryption_key() and use it in both generate_totp and reset_tpm cases

diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -81,6 +81,23 @@ confirm_totp()
 	echo
 }
 
+reseal_tpm_disk_decryption_key()
+{
+if [ -s /boot/kexec_key_devices.txt ] || [ -s /boot/kexec_key_lvm.txt ]; then
+	warn "A TPM disk decryption key previoulsy setuped is now invalid since firmware measurements changed. Renewing"
+	while ! kexec-seal-key /boot; do
+		warn "Recovery disk encryption key passphrase invalid. Try again!"
+	done
+	echo "LUKS header hash changed under of /boot/kexec_luks_hdr_hash.txt. Resigning /boot"
+	while ! update_checksums; do
+		warn "Checksums were not updated. Please re-sign!"
+	done
+	warn "Rebooting in 3 seconds to enable booting default boot option..."
+	sleep 3
+	reboot
+fi
+}
+
 # Enable USB storage (if not already enabled), and wait for storage devices to
 # be detected.  If USB storage was already enabled, no wait occurs, this would
 # have happened already when USB storage was enabled.
