Revert Makefile changes to test builds without calling bootstrap nor musl-cross make targets, which are not found when gawk and make are not rebuild locally on newer OSes Makefile as it was before fails building coreboot 4.11 while being successful for 4.13...Not understanding. 	Now unsuccessful for 4.13 in coreboot muslcross? 		CircleCI: Changing log output to files modified in last 5 minutes to catch log

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,7 +22,7 @@ commands:
       - run:
           name: Output build failing logs
           command: |
-            if [[ -f ./tmpDir/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi \
+            if [[ -f ./tmpDir/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -5|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi \
       - run:
           name: Output hashes
           command: |
