CircleCI: remove all boards but x230-external-flash

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -59,165 +59,165 @@ jobs:
 #      - store-artifacts:
 #          path: build/qemu-linuxboot/hashes.txt
 
-      - run:
-          name: librem_l1um
-          command: |
-            rm -rf build/librem_l1um/* build/log/* && make CPUS=4 V=1 BOARD=librem_l1um || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs 
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi \
-      - run:
-          name: Ouput librem_l1um hashes
-          command: |
-            cat build/librem_l1um/hashes.txt \
-      - run:
-          name: Archiving build logs for librem_l1um
-          command: |
-             tar zcvf build/librem_l1um/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/librem_l1um
-
-      - run:
-          name: librem_mini
-          command: |
-            rm -rf build/librem_mini/* build/log/* && make CPUS=4 V=1 BOARD=librem_mini || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Ouput librem_mini hashes
-          command: |
-            cat build/librem_mini/hashes.txt \
-      - run:
-          name: Archiving build logs for librem_mini
-          command: |
-             tar zcvf build/librem_mini/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/librem_mini
-
-      - run:
-          name: x230-flash
-          command: |
-            rm -rf build/x230-flash/* build/log/* && make CPUS=4 V=1 BOARD=x230-flash || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Ouput x230-flash hashes
-          command: |
-            cat build/x230-flash/hashes.txt \
-      - run:
-          name: Archiving build logs for x230-flash
-          command: |
-             tar zcvf build/x230-flash/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/x230-flash
-
-      - run:
-          name: t430-flash
-          command: |
-            rm -rf build/t430-flash/* build/log/* && make CPUS=4 V=1 BOARD=t430-flash || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Ouput t430-flash hashes
-          command: |
-            cat build/t430-flash/hashes.txt \
-      - run:
-          name: Archiving build logs for t430-flash
-          command: |
-             tar zcvf build/t430-flash/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/t430-flash
-
-      - run:
-          name: t430
-          command: |
-            rm -rf build/t430/* build/log/* && make CPUS=4 V=1 BOARD=t430 || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Ouput t430 hashes
-          command: |
-            cat build/t430/hashes.txt \
-      - run:
-          name: Archiving build logs for t430
-          command: |
-             tar zcvf build/t430/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/t430
-
-      - run:
-          name: x230
-          command: |
-            rm -rf build/x230/* build/log/* && make CPUS=4 V=1 BOARD=x230 || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Ouput x230 hashes
-          command: |
-            cat build/x230/hashes.txt \
-      - run:
-          name: Archiving build logs for x230
-          command: |
-             tar zcvf build/x230/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/x230
-
-      - run:
-          name: x230-hotp-verification
-          command: |
-            rm -rf build/x230-hotp-verification/* build/log/* && make CPUS=4 V=1 BOARD=x230-hotp-verification || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Ouput x230-hotp-verification hashes
-          command: |
-            cat build/x230-hotp-verification/hashes.txt \
-      - run:
-          name: Archiving build logs for x230-hotp-verification
-          command: |
-             tar zcvf build/x230-hotp-verification/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/x230-hotp-verification
-
-      - run:
-          name: x230-nkstorecli
-          command: |
-            rm -rf build/x230-nkstorecli/* build/log/* && make CPUS=4 V=1 BOARD=x230-nkstorecli || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Ouput x230-nkstorecli hashes
-          command: |
-            cat build/x230-nkstorecli/hashes.txt \
-      - run:
-          name: Archiving build logs for x230-nkstorecli
-          command: |
-             tar zcvf build/x230-nkstorecli/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/x230-nkstorecli
+#      - run:
+#          name: librem_l1um
+#          command: |
+#            rm -rf build/librem_l1um/* build/log/* && make CPUS=4 V=1 BOARD=librem_l1um || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs 
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi \
+#      - run:
+#          name: Ouput librem_l1um hashes
+#          command: |
+#            cat build/librem_l1um/hashes.txt \
+#      - run:
+#          name: Archiving build logs for librem_l1um
+#          command: |
+#             tar zcvf build/librem_l1um/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/librem_l1um
+#
+#      - run:
+#          name: librem_mini
+#          command: |
+#            rm -rf build/librem_mini/* build/log/* && make CPUS=4 V=1 BOARD=librem_mini || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+#      - run:
+#          name: Ouput librem_mini hashes
+#          command: |
+#            cat build/librem_mini/hashes.txt \
+#      - run:
+#          name: Archiving build logs for librem_mini
+#          command: |
+#             tar zcvf build/librem_mini/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/librem_mini
+#
+#      - run:
+#          name: x230-flash
+#          command: |
+#            rm -rf build/x230-flash/* build/log/* && make CPUS=4 V=1 BOARD=x230-flash || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+#      - run:
+#          name: Ouput x230-flash hashes
+#          command: |
+#            cat build/x230-flash/hashes.txt \
+#      - run:
+#          name: Archiving build logs for x230-flash
+#          command: |
+#             tar zcvf build/x230-flash/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/x230-flash
+#
+#      - run:
+#          name: t430-flash
+#          command: |
+#            rm -rf build/t430-flash/* build/log/* && make CPUS=4 V=1 BOARD=t430-flash || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+#      - run:
+#          name: Ouput t430-flash hashes
+#          command: |
+#            cat build/t430-flash/hashes.txt \
+#      - run:
+#          name: Archiving build logs for t430-flash
+#          command: |
+#             tar zcvf build/t430-flash/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/t430-flash
+#
+#      - run:
+#          name: t430
+#          command: |
+#            rm -rf build/t430/* build/log/* && make CPUS=4 V=1 BOARD=t430 || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+#      - run:
+#          name: Ouput t430 hashes
+#          command: |
+#            cat build/t430/hashes.txt \
+#      - run:
+#          name: Archiving build logs for t430
+#          command: |
+#             tar zcvf build/t430/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/t430
+#
+#      - run:
+#          name: x230
+#          command: |
+#            rm -rf build/x230/* build/log/* && make CPUS=4 V=1 BOARD=x230 || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+#      - run:
+#          name: Ouput x230 hashes
+#          command: |
+#            cat build/x230/hashes.txt \
+#      - run:
+#          name: Archiving build logs for x230
+#          command: |
+#             tar zcvf build/x230/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/x230
+#
+#      - run:
+#          name: x230-hotp-verification
+#          command: |
+#            rm -rf build/x230-hotp-verification/* build/log/* && make CPUS=4 V=1 BOARD=x230-hotp-verification || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+#      - run:
+#          name: Ouput x230-hotp-verification hashes
+#          command: |
+#            cat build/x230-hotp-verification/hashes.txt \
+#      - run:
+#          name: Archiving build logs for x230-hotp-verification
+#          command: |
+#             tar zcvf build/x230-hotp-verification/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/x230-hotp-verification
+#
+#      - run:
+#          name: x230-nkstorecli
+#          command: |
+#            rm -rf build/x230-nkstorecli/* build/log/* && make CPUS=4 V=1 BOARD=x230-nkstorecli || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+#      - run:
+#          name: Ouput x230-nkstorecli hashes
+#          command: |
+#            cat build/x230-nkstorecli/hashes.txt \
+#      - run:
+#          name: Archiving build logs for x230-nkstorecli
+#          command: |
+#             tar zcvf build/x230-nkstorecli/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/x230-nkstorecli
 
       - run:
           name: x230-external-flash
@@ -237,45 +237,45 @@ jobs:
       - store-artifacts:
           path: build/x230-external-flash
 
-      - run:
-          name: qemu-coreboot
-          command: |
-            rm -rf build/qemu-coreboot/* build/log/* && make CPUS=4 V=1 BOARD=qemu-coreboot || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output qemu-coreboot hashes
-          command: |
-             cat build/qemu-coreboot/hashes.txt \
-      - run:
-          name: Archiving build logs for qemu-coreboot
-          command: |
-             tar zcvf build/qemu-coreboot/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/qemu-coreboot
-
-      - run:
-          name: qemu-coreboot-fbwhiptail
-          command: |
-            rm -rf build/qemu-coreboot-fbwhiptail/* build/log/* && make CPUS=4 V=1 BOARD=qemu-coreboot-fbwhiptail || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Ouput build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output qemu-coreboot-fbwhiptail hashes
-          command: |
-             cat build/qemu-coreboot-fbwhiptail/hashes.txt \
-      - run:
-          name: Archiving build logs for qemu-coreboot-fbwhiptail
-          command: |
-             tar zcvf build/qemu-coreboot-fbwhiptail/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/qemu-coreboot-fbwhiptail
+#      - run:
+#          name: qemu-coreboot
+#          command: |
+#            rm -rf build/qemu-coreboot/* build/log/* && make CPUS=4 V=1 BOARD=qemu-coreboot || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+#      - run:
+#          name: Output qemu-coreboot hashes
+#          command: |
+#             cat build/qemu-coreboot/hashes.txt \
+#      - run:
+#          name: Archiving build logs for qemu-coreboot
+#          command: |
+#             tar zcvf build/qemu-coreboot/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/qemu-coreboot
+#
+#      - run:
+#          name: qemu-coreboot-fbwhiptail
+#          command: |
+#            rm -rf build/qemu-coreboot-fbwhiptail/* build/log/* && make CPUS=4 V=1 BOARD=qemu-coreboot-fbwhiptail || touch /tmp/failed_build
+#          no_output_timeout: 3h
+#      - run:
+#          name: Ouput build failing logs
+#          command: |
+#            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+#      - run:
+#          name: Output qemu-coreboot-fbwhiptail hashes
+#          command: |
+#             cat build/qemu-coreboot-fbwhiptail/hashes.txt \
+#      - run:
+#          name: Archiving build logs for qemu-coreboot-fbwhiptail
+#          command: |
+#             tar zcvf build/qemu-coreboot-fbwhiptail/logs.tar.gz build/log/*
+#      - store-artifacts:
+#          path: build/qemu-coreboot-fbwhiptail
 
       - save_cache:
           #Generate cache for the same musl-cross module definition if hash is not previously existing
